In [1]:
import pandas as pd
import re

In [2]:
def attendance(x):
    x = x.replace('-','')
    l = list(set(re.findall(r'\b[0-9]{13}\b',x)))
    return pd.DataFrame({"CNIC":l})

In [3]:
x = """
Ali Yaqoob3:58 PM
not from IT
Imran Ejaz3:58 PM
no from accounting.
Zeeshan Yaseen3:58 PM
Prediction and automation !
Ali Yaqoob3:59 PM
Automation, hence accuracy plus time saving.
Ali Yaqoob4:09 PM
chatgpt se hi search kerlen ge üòÅ
Ali Yaqoob4:21 PM
aammeen
Aijaz Ahmed5:36 PM
4520691925699
Abdulrafay Memon5:36 PM
45204-3483907-1
Zeeshan Yaseen5:36 PM
4220141892019
Syed Muzammil Haider5:36 PM
4210149039311
ShahzadAzam Hashmi5:36 PM
36302-4791284-7
Ali Yaqoob5:36 PM
4210150317619
M. A. Miher5:36 PM
3720117887067
syed daniyal5:36 PM
4250189782769
Dr Nadeem Shah5:36 PM
4130464926599
Iqra Talha5:37 PM
6110120315128
Sibtain Ahmed5:37 PM
41303-5613312-5
Imran Ejaz5:37 PM
Imran Ejaz 4200044884823
Ali Jilani5:37 PM
42201-1405671-9
Sundus Baloch5:37 PM
41201-0883673-2
Suhail Arif5:37 PM
Suhail Arif Hussain 422017677201
Sadiq Fazal5:37 PM
42101-7245686-0
Zain Naqvi5:37 PM
4220147830681
salman soorani5:37 PM
4210124505207
Umer Fariq5:37 PM
4220122685447
Hassan Qamar5:37 PM
Hassan Qamar 4220110629561
wardah siddiqui5:37 PM
4210166120772
muhammad anas5:37 PM
4210113165975
Saad Shoaib5:37 PM
41304-1401693-1
Nasir Ali5:37 PM
4330401845851
Fahad Aziz Khan5:38 PM
4220195795061
Muhammad Haneef5:38 PM
42201-3466487-5
MARYAM RASHID5:38 PM
42101-9854842-0
ehzam ahmed5:38 PM
42201-7632311-1
Ali Jilani5:38 PM
4220114056719
Raheel Sadruddin5:38 PM
4210129790553
Waleed Ahmed Siddiqui5:38 PM
4210195297779
Munir Mirza5:38 PM
42101-0575629-9
Hassan Saleem5:38 PM
42101-9952553-5
Ahmed Ali5:38 PM
42101-0724035-9
Hassan Qamar5:38 PM
4220110629561
Raheel Sadruddin5:38 PM
4210105390867
Mohsin Kamal5:39 PM
4230108855633
Arsalan Shaikh5:39 PM
42201-6205339-3
Ayaz Muhammad5:39 PM
45202-8263294-7 
Muhammad Ayaz
Present
Nasir Ali5:39 PM
4330401845851
Sadaf Tirmizi5:39 PM
42101-7246731-0
Sheza Shams5:39 PM
42201-0218814-0
Ayaz Muhammad5:39 PM
45202826329467
Zubair ,5:40 PM
1310104942039
Noman Younus5:40 PM
4220102372205
Suhail Arif5:40 PM
4220176777201
osama saleem5:40 PM
42201-8286143-9
42101-1693504-9
4220188550515
Muneeb Bhania5:41 PM
42101-3818298-7
Sundus Baloch5:41 PM
4120108836732
usama hanif5:41 PM
42101-3220905-9
Muneeb Bhania5:41 PM
42501-7775696-8
Ahmer Tariq5:41 PM
42201-3054964-3
Nasir Ali5:41 PM
Kamran
4230122270821
Umair Sajid5:41 PM
42201-1539594-3
Misbah Sabir5:42 PM
42101-5742100-4
Nasir Ali5:42 PM
Hassan
4240134843465
Misbah Sabir5:42 PM
42101-5802137-4
Qureshi Kainat5:42 PM
5540124860782
Misbah Sabir5:42 PM
4220108354184
Engr Mahmood Ul Hassan5:43 PM
4250185234859
Qureshi Kainat5:43 PM
4210157421004
Mohsin Kamal5:43 PM
4230108855633
Qureshi Kainat5:43 PM
4220187822116
4220178140796
upq-oxma-vmi
"""
df1 = attendance(x)
df1['c1'] = 1
print(len(df1))
df1.head()

58

            CNIC  c1
0  4220108354184   1
1  4210105390867   1
2  4210107240359   1
3  4520282632947   1
4  4520434839071   1

# Class2

In [4]:
x = """
Ahtisham Ali Khan3:49 PM
Present
Kamran Younus4:06 PM
Muhammad Kamran Younus 42301-2227082-1
Abdulrafay Memon4:10 PM
45204-3483907-1
Athar Khalid4:10 PM
why nic no?
Fahad Aziz Khan4:14 PM
its called Proprietary Products/Applications
Umer Fariq4:20 PM
cant see the shared screen
Imran Ejaz4:21 PM
Share the screen
Athar Khalid4:26 PM
gmail address is fine , sir
Kamran Younus4:30 PM
Anaconda 32 bit windows pe download ho Jaye ga?
Ifra Siddiqui4:36 PM
can you repeat once again?
M. A. Miher4:39 PM
print("Hello World?")
Imran Ejaz4:42 PM
sir jupitar per likh sukty hain?
Athar Khalid4:44 PM
done
Abdulrafay Memon4:50 PM
ji sir
Athar Khalid5:06 PM
recording drive pe share krdi  ha
Suhail Arif5:28 PM
4220176777201
insharah khan5:28 PM
4210131827012
Sundus Baloch5:28 PM
4120108835732
Ali Nawaz5:28 PM
4220157226073
Ayaz Muhammad5:28 PM
45202-8263294-7
M. A. Miher5:28 PM
3720117887067
Imran Ejaz5:28 PM
4200044884823
Muhammad Haneef5:28 PM
4220134664875
Nasir Ali5:28 PM
4330401845851
ShahzadAzam Hashmi5:28 PM
3630247912847
Mahnoor Arif5:28 PM
4220178140796
Farooq Ahmad5:28 PM
3520294446451
Noman Younus5:28 PM
4220102372205
Ifra Siddiqui5:28 PM
4250177756968
muhammad anas5:29 PM
4210113165975
Sibtain Ahmed5:29 PM
4130356133125
Abdul Mannan Khan5:29 PM
4220143572841
Abdulrafay Memon5:29 PM
4520434839071
daniyal5:29 PM
4250189782769
Zubair ,5:29 PM
1310104942039
Misbah Sabir5:29 PM
4210158021374
Fahad Aziz Khan5:29 PM
422019579065
salman soorani5:29 PM
4210124505207
Hassan Saleem5:29 PM
42101-9952553-5
Asad Khan5:29 PM
3830155517583
Athar Khalid5:29 PM
4210158892613
Fuzail Muzaffar5:29 PM
4250181112217
Sadiq Fazal5:29 PM
42101-7245686-0
Abdul Haseeb Khan5:29 PM
4220103084339
Farah Asif5:29 PM
3740680876662
Qureshi Kainat5:29 PM
5540124860782
Umair Sajid5:29 PM
4220115395943
osama saleem5:29 PM
4220182861439
ehzam ahmed5:29 PM
4220176323111
Saad Shoaib5:29 PM
4130414016931
Zafar Abbas5:29 PM
Zafar Abbas
Muneeb Bhania5:29 PM
4210138182987
Umer Fariq5:29 PM
4220122685447
Sadaf Tirmizi5:29 PM
42101-7245781-0
Atif Khan5:29 PM
4210102810113
Raheel Sadruddin5:29 PM
4210129790553
Hassan Qamar5:29 PM
4220110629561
Dr Nadeem Shah5:29 PM
4130464926599
wardah siddiqui5:29 PM
4210166120772
Mohsin Kamal5:29 PM
4230108855633
Munir Soorani5:29 PM
42101-0575629-9
Engr Mahmood Ul Hassan5:29 PM
4250185234859
Zafar Abbas5:29 PM
Zafar Abbas
37405-2371844-9
usama hanif5:29 PM
42101-3220905-9
Farah Asif5:29 PM
4210157421004
Ali Jilani5:29 PM
4220114056719
SHAHRUKH KHAN5:29 PM
4210105390867
Atif Khan5:30 PM
Atif shahzad 4210102810113
Raja Waleed5:30 PM
4220188550515
SHAHRUKH KHAN5:30 PM
4210116935049
Arsalan Shaikh5:30 PM
42201-6205339-3
Farah Asif5:30 PM
4220187822116
Syed Muzammil Haider5:30 PM
4210149039311
Farah Asif5:30 PM
4320307738760
Sadaf Tirmizi5:31 PM
42101-7245781-0
Maria Noor Amjad5:31 PM
61101-1956982-0
Syed Muzammil Haider5:31 PM
4210172457810
Aimen Iftikhar5:31 PM
Aimen
4220177849728
Sheza Shams5:31 PM
4220102188140
Rida Batool5:31 PM
42101-7245781-0
Umair Sajid5:32 PM
4140703835369
Mohsin Kamal5:32 PM
4230108855633
Umair Sajid5:32 PM
42101-2548111-7
Ahmed Ali5:32 PM
42101-0724035-9
Nasir Ali5:32 PM
Muhammad Sameer
4230135829705
Ali Yaqoob5:32 PM
4210150317619
obaid rehman5:34 PM
4240113406009
3630230577559
upq-oxma-vmi
"""
df2 = attendance(x)
print(len(df2))
df2['c2'] = 1
df2.head()

67

            CNIC  c2
0  4210131827012   1
1  3740523718449   1
2  4210105390867   1
3  4220103084339   1
4  4520282632947   1

In [5]:
x = """
Engr Mahmood Ul Hassan4:00‚ÄØPM
4250185234859
Abdul Haseeb Khan4:01‚ÄØPM
4220103084339
amir sohail4:01‚ÄØPM
4140703835369
Fahad Aziz Khan4:01‚ÄØPM
4220195795065
Usama Ahmed4:01‚ÄØPM
61101-9688391-5
Hina Hyder4:01‚ÄØPM
43203-0773876-0
Saad Shoaib4:02‚ÄØPM
4130414016931
M. A. Miher4:02‚ÄØPM
3720117887067
sadia faiyaz4:02‚ÄØPM
yes
Ali Jilani4:02‚ÄØPM
Jee sir
4220114056719
Athar Khalid4:02‚ÄØPM
4210158892613
Suhail Arif4:02‚ÄØPM
Suhail Arif Hussain 422017677201
Farah Asif4:03‚ÄØPM
3740680876662
Imran Ejaz4:03‚ÄØPM
4200044884823
Ali Yaqoob4:04‚ÄØPM
4210150317619
Umair Sajid4:04‚ÄØPM
42201-1539594-3
Farooq Ahmad4:04‚ÄØPM
3520294446451
Ayaz Muhammad4:05‚ÄØPM
4520282632947
Abdul Mannan Khan4:05‚ÄØPM
4220143572841
Muhammad Uzair4:05‚ÄØPM
4210125481117
osama saleem4:07‚ÄØPM
4220182861439
M. A. Miher4:10‚ÄØPM
screen not shared
Ali Yaqoob4:17‚ÄØPM
games
Abdul Haseeb Khan4:17‚ÄØPM
Car's make model variant
are attributes
Ali Yaqoob4:21‚ÄØPM
Function :  How to use
Attribute : How to identify
Muhammad Usama4:28‚ÄØPM
Sir, I have some issues with microphone
Can we do the same on Google Colab
instead of Jupyter Notebook
Ali Yaqoob4:36‚ÄØPM
yes
Muhammad Usama4:48‚ÄØPM
difference between double quote and single quote ?
Sheza Shams4:51‚ÄØPM
sir, you dont need inverted commas for integer and float?
M. A. Miher4:52‚ÄØPM
date or time?
Muhammad Usama4:54‚ÄØPM
yes
insharah khan4:55‚ÄØPM
kindly share link of class
Sheikh Meraj Uddin4:56‚ÄØPM
Class Code please
Ali Yaqoob4:56‚ÄØPM
https://classroom.google.com/c/NTgxNTQxNjg4MTA2
Sheikh Meraj Uddin4:57‚ÄØPM
not connected
Ali Yaqoob4:57‚ÄØPM
sir i m already viewing it
Muhammad Usama4:58‚ÄØPM
username
Sheikh Meraj Uddin4:58‚ÄØPM
skmairaj@gmail.com
Ali Yaqoob4:59‚ÄØPM
aap login hain already?
Muhammad Usama4:59‚ÄØPM
I was just telling example for a variable
pictures
Owais Ahmed5:00‚ÄØPM
class code no?
Ali Yaqoob5:00‚ÄØPM
https://classroom.google.com/c/NTgxNTQxNjg4MTA2

complete link
Sheikh Meraj Uddin5:00‚ÄØPM
logged in on meet
Owais Ahmed5:00‚ÄØPM
owaisahmed783@gmail.com
Ali Yaqoob5:01‚ÄØPM
sir usi browser mai new tab mai try kerain yeh link
Sheikh Meraj Uddin5:05‚ÄØPM
Still class not found
Ali Yaqoob5:07‚ÄØPM
sir its permission issue i guess then
Sheikh Meraj Uddin5:07‚ÄØPM
May b
Ali Yaqoob5:08‚ÄØPM
coz i have tried by using another ID and observed the same error 'class not found'.
Muhammad Usama5:21‚ÄØPM
sir integer k liye yeh ID nahi aati ?
Engr Mahmood Ul Hassan5:23‚ÄØPM
Memory size?
Aijaz Ahmed5:24‚ÄØPM
no memoery address
Muhammad Usama5:26‚ÄØPM
# detay hain
Sir attendance laga den
Zeeshan Yaseen5:34‚ÄØPM
variable
Muhammad Usama5:34‚ÄØPM
variable
Hassan Qamar5:43‚ÄØPM
4220110629561
Ali Nawaz5:44‚ÄØPM
4220157226073
Noor Saba5:44‚ÄØPM
4220187822116
Zeeshan Yaseen5:44‚ÄØPM
yes
amir sohail5:44‚ÄØPM
4240113406009
daniyal5:44‚ÄØPM
4250189782769
Dr Nadeem Shah5:44‚ÄØPM
4130464926599
Raja Waleed5:45‚ÄØPM
422018855055
sadia faiyaz5:45‚ÄØPM
4210157421004
Fuzail Muzaffar5:45‚ÄØPM
4250181112217
salman soorani5:45‚ÄØPM
4210124505207
Munir Mirza5:45‚ÄØPM
42101-0575629-9
Muhammad Haneef5:45‚ÄØPM
4220134664875
Arsalan Shaikh5:45‚ÄØPM
42201-6205339-3
Muneeb Bhania5:45‚ÄØPM
4210138182987
Insharah Khan5:46‚ÄØPM
4210131827012
ShahzadAzam Hashmi5:46‚ÄØPM
3630247912847
Muneeb Bhania5:46‚ÄØPM
4250177756968
ehzam ahmed5:46‚ÄØPM
4220176323111
Imran Ejaz5:46‚ÄØPM
4200044884823
Maria Noor Amjad5:46‚ÄØPM
6110119569820
Mahnoor Arif5:47‚ÄØPM
4220178140796
Qureshi Kainat5:47‚ÄØPM
5540124860782
Zeeshan Yaseen5:47‚ÄØPM
4220141892019
Nasir Ali5:47‚ÄØPM
4330401845851
Ali Yaqoob5:47‚ÄØPM
4210150317619
Mohsin Kamal5:47‚ÄØPM
4230108855633
Abdul Mannan Khan5:47‚ÄØPM
4220143572841
Muhammad Usama5:47‚ÄØPM
4220115395943
osama saleem5:47‚ÄØPM
4220182861439
SHAHRUKH KHAN5:47‚ÄØPM
4210105390867
Aijaz Ahmed5:47‚ÄØPM
4520691925699
muhammad anas5:47‚ÄØPM
4210113165975
Hina Hyder5:47‚ÄØPM
43203-0773876-0
Zubair ,5:47‚ÄØPM
1310104942039
Raheel Sadruddin5:47‚ÄØPM
4210129790553
Umer Fariq5:47‚ÄØPM
4220122685447
Hassan Saleem5:47‚ÄØPM
4210199525535
Ahsan Fayyaz5:47‚ÄØPM
4220115069023
Sibtain Ahmed5:47‚ÄØPM
4130356133125
Syed Muzammil Haider5:47‚ÄØPM
4210149039311
Rida Batool5:47‚ÄØPM
42101-7245781-0
Suhail Arif5:47‚ÄØPM
Suhail Arif Hussain 4220176777201
Saad Shoaib5:47‚ÄØPM
4130414016931
Wajid Khan5:47‚ÄØPM
42101-1693504-9
usama hanif5:47‚ÄØPM
42101-3220905-9
Sadiq Fazal5:47‚ÄØPM
42101-7245686-0
Misbah Sabir5:47‚ÄØPM
4210158021374
Usama Ahmed5:48‚ÄØPM
6110196883915
Noman Younus5:48‚ÄØPM
4220102372205
Nasir Ali5:48‚ÄØPM
Muhammad Hasan
4240134843465
Sheza Shams5:48‚ÄØPM
42201-0218814-0
Ali Mehdi5:48‚ÄØPM
4220193871331
Mohsin Kamal5:48‚ÄØPM
4230108855633
Sheikh Meraj Uddin5:49‚ÄØPM
4210192333399
Owais Ahmed5:49‚ÄØPM
Syed Owais Ahmed
42201-0319489-3
Rida Batool5:49‚ÄØPM
4210172457810
Kamran Younus5:49‚ÄØPM
4230122270821
Iqra Talha5:50‚ÄØPM
6110120315128
upq-oxma-vmi
"""

df3 = attendance(x)
print(len(df3))
df3['c3'] = 1
df3.head()

66

            CNIC  c3
0  4210131827012   1
1  4220103084339   1
2  4520282632947   1
3  3740680876662   1
4  4130414016931   1

In [6]:
x = """
Sibtain Ahmed5:20‚ÄØPM
4130356133125
Muhammad Haneef5:21‚ÄØPM
No Sir
Engr Mahmood Ul Hassan5:21‚ÄØPM
4250185234859
Ahmed Ali5:22‚ÄØPM
42101-0724035-9
Ali Jilani5:22‚ÄØPM
4220114056719
Athar Khalid5:23‚ÄØPM
4210158892613
Ali Affan Yaqoob5:23‚ÄØPM
4210150317619
Muhammad Hasan5:26‚ÄØPM
4240134843465
Areeba Ghazal5:26‚ÄØPM
4220108354184
Qureshi Kainat5:26‚ÄØPM
5540124860782
Raja Waleed5:26‚ÄØPM
4220188550515
Abdulrafay Memon5:27‚ÄØPM
4520434839071
Suhail Arif5:27‚ÄØPM
Suhail Arif HUssain 4220176777201
Abdul Haseeb Khan5:27‚ÄØPM
4220103084339
NASIR ALI5:27‚ÄØPM
4330401845851
Munir Mirza5:27‚ÄØPM
42101-0575629-9
Ali Jilani5:27‚ÄØPM
4220114056719
Dr Nadeem Shah5:27‚ÄØPM
4130464926599
Muhammad Uzair5:30‚ÄØPM
4210125481117
Ali Jilani5:31‚ÄØPM
Camel notations
Abdulrafay Memon5:33‚ÄØPM
4520434839071
Hina Hyder5:47‚ÄØPM
43203-0773876-0
daniyal5:47‚ÄØPM
4250189782769
Misbah Sabir5:47‚ÄØPM
4210158021374
Muneeb Bhania5:47‚ÄØPM
4210138182987
Abdul Mannan Khan5:47‚ÄØPM
4220143572841
Fuzail Muzaffar5:48‚ÄØPM
4250181112217
Imran Ejaz5:48‚ÄØPM
4200044884823
ShahzadAzam Hashmi5:48‚ÄØPM
36302-4791284-7
Zeeshan Yaseen5:52‚ÄØPM
PLACEHOLDERS
Arsalan Shaikh5:52‚ÄØPM
42201-6205339-3
Maria Noor Amjad5:52‚ÄØPM
6110119569820
amir sohail5:53‚ÄØPM
4140703835369
Aimen Iftikhar5:53‚ÄØPM
42201-7784972-8
Aijaz Ahmed5:53‚ÄØPM
Age, capitalize A
Muhammad Haneef5:55‚ÄØPM
4220134664875
Ali Nawaz5:55‚ÄØPM
4220157226073
Hassan Qamar5:59‚ÄØPM
4220110629561
osama saleem6:00‚ÄØPM
4220182861439
sadia faiyaz6:00‚ÄØPM
4210157421004
Hassan Saleem6:00‚ÄØPM
4210199525535
Iqra Talha6:01‚ÄØPM
6110120315128
ali soorani6:01‚ÄØPM
4210124505207
Insharah Khan6:01‚ÄØPM
4210131827012
Ali Mehdi6:04‚ÄØPM
4220193871331
Owais Ahmed6:05‚ÄØPM
4220103194893
Waleed Ahmed Siddiqui6:05‚ÄØPM
4210195297779
Engr Mahmood Ul Hassan6:06‚ÄØPM
Namaz break
Sheikh Meraj Uddin6:06‚ÄØPM
4210192333399
Farah Asif6:06‚ÄØPM
3740680876662
Fahad Aziz Khan6:07‚ÄØPM
4220195795065
Misbah Sabir6:20‚ÄØPM
sir my mic is not working I  have a question agr hmare pas bht bara data ha to hm indexing ya sequencing kese krenge like its time taking to count
daniyal6:21‚ÄØPM
kindly define tuple
kindly define sequence and list of python
daniyal6:22‚ÄØPM
why we use % sign
daniyal6:24‚ÄØPM
why use F 
daniyal6:25‚ÄØPM
anyone can ask from sir why we use f""''
daniyal6:29‚ÄØPM
no sir
file import and and dataframe show karwaya hai
ali soorani6:33‚ÄØPM
your voice gone
Ali Affan Yaqoob6:34‚ÄØPM
ali bhai aap k net ka issue hoga maybe. yahan tau audible hain sir
daniyal6:39‚ÄØPM
what is tuple
Ali Affan Yaqoob6:39‚ÄØPM
sir ne kaha hai k bad mai batayen ge
its too early for that
Zaib Batool6:42‚ÄØPM
42101-7245686-0
Dr Nadeem Shah6:42‚ÄØPM
4130464926599
daniyal6:42‚ÄØPM
do we do regular expression in this course ?
Raheel Sadruddin6:42‚ÄØPM
4210129790553
wardah siddiqui6:43‚ÄØPM
4210166120772
Muneeb Bhania6:43‚ÄØPM
4210138182987
Wajid Khan6:49‚ÄØPM
42101-1693504-9
Sibtain Ahmed6:51‚ÄØPM
4130356133125
daniyal6:53‚ÄØPM
yes sir
tru
true
daniyal6:55‚ÄØPM
\t means and why we use tap
space
in formation
Saad Shoaib6:57‚ÄØPM
4130414016931
Engr Mahmood Ul Hassan6:57‚ÄØPM
4250185234859
Raja Waleed6:57‚ÄØPM
4220188550515
Saad Shoaib6:57‚ÄØPM
4130414016931
Abdul Haseeb Khan6:57‚ÄØPM
4220103084339
Zubair ,6:57‚ÄØPM
1310104942039
Abdul Mannan Khan6:57‚ÄØPM
4220143572841
Ali Affan Yaqoob6:57‚ÄØPM
42101-5031761-9
Ali Nawaz6:58‚ÄØPM
4220157226073
Mohsin Kamal6:58‚ÄØPM
4230108855633
ali soorani6:58‚ÄØPM
4210124505207
Noor Saba6:58‚ÄØPM
4220187822116
Usama Ahmed6:58‚ÄØPM
61101-9688391-5
muhammad anas6:58‚ÄØPM
4210113165975
Imran Ejaz6:58‚ÄØPM
4200044884823
Hassan Qamar6:58‚ÄØPM
4220110629561
Nasir Ali6:58‚ÄØPM
4330401845851
Abdulrafay Memon6:58‚ÄØPM
4520434839071
Noman Younus6:58‚ÄØPM
4220102372205
Sibtain Ahmed6:58‚ÄØPM
4130356133125
Dr Nadeem Shah6:58‚ÄØPM
4130464926599
Fahad Aziz Khan6:58‚ÄØPM
4220195795065
Ahtisham Ali Khan6:58‚ÄØPM
3830155517583
Aijaz Ahmed6:58‚ÄØPM
4520691925699
Raja Waleed6:58‚ÄØPM
4220188550515
Zeeshan Yaseen6:58‚ÄØPM
4220141892019
Mahnoor Arif6:58‚ÄØPM
4220178140796
Insharah Khan6:59‚ÄØPM
4210131827012
Syed Muzammil Haider6:59‚ÄØPM
4210149039311
Misbah Sabir6:59‚ÄØPM
4210158021374
SHAHRUKH KHAN6:59‚ÄØPM
4210105390867
osama saleem6:59‚ÄØPM
4220182861439
Athar Khalid6:59‚ÄØPM
4210158892613
Rida Batool6:59‚ÄØPM
4210172457810
Noman Younus6:59‚ÄØPM
4210105756299
ShahzadAzam Hashmi6:59‚ÄØPM
3630247912847
Sheza Shams6:59‚ÄØPM
42201-0218814-0
Raheel Sadruddin6:59‚ÄØPM
4210129790553
Suhail Arif6:59‚ÄØPM
suhail arif hussain 4220176777201
Mohsin Kamal6:59‚ÄØPM
4230108855633
ifra siddiqui6:59‚ÄØPM
4250177756958
usama hanif6:59‚ÄØPM
42101-3220905-9
wardah siddiqui6:59‚ÄØPM
4210166120772
Ahmed Ali6:59‚ÄØPM
4210107240359
Hina Hyder6:59‚ÄØPM
hina hyder 43203-0773876-0
Muhammad Hasan7:00‚ÄØPM
4240134843465
upq-oxma-vmi"""

df4 = attendance(x)
print(len(df4))
df4['c4'] = 1
df4.head()

65

            CNIC  c4
0  4220108354184   1
1  4210131827012   1
2  4210105390867   1
3  4220103084339   1
4  3740680876662   1

In [7]:
x = """
Suhail Arif4:08‚ÄØPM
Suhail Arif Hussain 4220176777201
Wajid Khan4:09‚ÄØPM
42101-1693504-9
Areeba Ghazal4:09‚ÄØPM
4220108354184
Umair Sajid4:09‚ÄØPM
4220115395943
MAAZ AHMED4:09‚ÄØPM
attendance? Roll No	AIC036044
Athar Khalid4:10‚ÄØPM
4210158892613
Ali Affan Yaqoob4:10‚ÄØPM
42101-5031761-9
Athar Khalid4:13‚ÄØPM
casting
Sadaf Tirmizi4:13‚ÄØPM
42101-7246731-0
Ali Jilani4:14‚ÄØPM
4220114056719
Muhammad Uzair4:15‚ÄØPM
4210125481117
Aimen Iftikhar4:15‚ÄØPM
42201 77849728
Sadaf Tirmizi4:16‚ÄØPM
4210172457810
Ahmed Ali4:16‚ÄØPM
42101-0724035-9
Qureshi Kainat4:16‚ÄØPM
5540124860782
osama saleem4:17‚ÄØPM
4220182861439
Rida Batool4:17‚ÄØPM
4210172457810
Rida Batool4:18‚ÄØPM
4210172456860
Aimen Iftikhar4:20‚ÄØPM
You have converted type int to str
Sheikh Meraj Uddin4:23‚ÄØPM
4210192333399
Farah Asif4:23‚ÄØPM
3740680876662
dani4:23‚ÄØPM
4250189782769
Ayaz Muhammad4:24‚ÄØPM
4520282632947
MAAZ AHMED4:27‚ÄØPM
why CNIC number?
Umair Sajid4:28‚ÄØPM
asterik
Muhammad Haris Bin Khalid4:28‚ÄØPM
42101-0124403-1 (Haris Khalid)
Sameer abid4:29‚ÄØPM
Muhammad Sameer
ShahzadAzam Hashmi4:29‚ÄØPM
3630247912847
Muneeb Bhania4:29‚ÄØPM
4210138182987
Sameer abid4:29‚ÄØPM
Muhammad Sameer 4230135829705
MAAZ AHMED4:29‚ÄØPM
https://www.collinsdictionary.com/dictionary/english/asterisk An asterisk is the sign *. It is used especially to indicate that there is further information about something in another part of the text.
Mohsin Kamal4:38‚ÄØPM
4230108855633
MAAZ AHMED4:53‚ÄØPM
break 5 min
https://www.w3schools.com/python/python_operators.asp
Muhammad Hasan4:55‚ÄØPM
4240134843465
Abdul Haseeb Khan4:55‚ÄØPM
4220103084339
Engr Mahmood Ul Hassan5:00‚ÄØPM
4250185234859
Muneeb Bhania5:01‚ÄØPM
4210138182987
Misbah Sabir5:02‚ÄØPM
4210158021374
Ali Mehdi5:02‚ÄØPM
4220193871331
Owais Ahmed5:08‚ÄØPM
4220103194893
Imran Ejaz5:08‚ÄØPM
4200044884823
MAAZ AHMED5:08‚ÄØPM
Why sharing CNIC numbers?
Muhammad Uzair5:08‚ÄØPM
for attendence
Ali Affan Yaqoob5:08‚ÄØPM
MAAZ BHAI ATTENDANCE ESE HI LAGAY GI
Imran Ejaz5:08‚ÄØPM
attendance
Hassan Qamar5:08‚ÄØPM
4220110629561
NASIR ALI5:09‚ÄØPM
4330401845851
Abdul Mannan Khan5:09‚ÄØPM
4220143572841
muhammad anas5:09‚ÄØPM
4210113165975
obaid rehman5:09‚ÄØPM
4240113406009
Hassan Saleem5:10‚ÄØPM
4210199525535
osama saleem5:14‚ÄØPM
4220182861439
wardah siddiqui5:15‚ÄØPM
4210166120772
MAAZ AHMED5:15‚ÄØPM
42201-8174960-1 MAAZ AHMED
Iqra Talha5:15‚ÄØPM
6110120315128
Sibtain Ahmed5:16‚ÄØPM
4130356133125
Noman Younus5:16‚ÄØPM
4220102372205
Zeeshan Yaseen5:17‚ÄØPM
4220141892019
Ali Nawaz5:17‚ÄØPM
4220157226073
Maria Noor Amjad5:17‚ÄØPM
6110119569820
obaid rehman5:23‚ÄØPM
36302-3057755-9
Munir Mirza5:29‚ÄØPM
42101-0575629-9
Hina Hyder5:30‚ÄØPM
hina hyder
Sheza Shams5:30‚ÄØPM
42201-0218814-0
Hina Hyder5:30‚ÄØPM
43203-0773876-0
hina hyder
SHAHRUKH KHAN5:30‚ÄØPM
4210105390867
Raja Waleed5:31‚ÄØPM
42201-8855051-5
Dr Nadeem Shah5:32‚ÄØPM
41304-6492659-9
Abdul Mannan Khan5:34‚ÄØPM
4220143572841
Ifra Siddiqui5:34‚ÄØPM
4250177756968
Ali Affan Yaqoob5:36‚ÄØPM
42101-5031761-9
Umer Fariq5:37‚ÄØPM
4220122685447
Mohsin Kamal5:37‚ÄØPM
4230108855633
ehzam ahmed5:37‚ÄØPM
4220176323111
M. A. Miher5:37‚ÄØPM
3720117887067
Zubair ,5:37‚ÄØPM
1310104942039
Raheel Sadruddin5:37‚ÄØPM
4210129790553
NASIR ALI5:37‚ÄØPM
4330401845851
Munir Mirza5:37‚ÄØPM
42101-0575629-9
Abdul Haseeb Khan5:37‚ÄØPM
4220103084339
ShahzadAzam Hashmi5:37‚ÄØPM
3630247912847
Ahtisham Ali Khan5:37‚ÄØPM
3830155517583
Umair Sajid5:37‚ÄØPM
42201-1539594-3 Umair Sajid
Saad Shoaib5:37‚ÄØPM
41304-1401693-1
Noor Saba5:37‚ÄØPM
4220187822116
Syed Muzammil Haider5:37‚ÄØPM
4210149039311
Usama Ahmed5:37‚ÄØPM
61101-9688391-5
Suhail Arif5:37‚ÄØPM
Suail Arif Hussain 4220176777201
ali soorani5:37‚ÄØPM
4210124505207
Mahnoor Arif5:37‚ÄØPM
4220178140796
Ali Jilani5:37‚ÄØPM
4220114056719
Ali Nawaz5:37‚ÄØPM
4220157226073
Fahad Aziz Khan5:37‚ÄØPM
4220195795065
usama hanif5:37‚ÄØPM
42101-3220905-9
NASIR ALI5:38‚ÄØPM
4240134843465
Muhammad Haris Bin Khalid5:38‚ÄØPM
42101-0124403-1
Noman Younus5:38‚ÄØPM
4220102372205
Misbah Sabir5:38‚ÄØPM
4210158021374
Ahtisham Ali Khan5:38‚ÄØPM
3830155517583
MAAZ AHMED5:38‚ÄØPM
ONSITE / PHYSICAL CLASS HOI HAY KOI ABHI TAK ?
MARYAM RASHID5:39‚ÄØPM
4210198548420
Ayaz Muhammad5:39‚ÄØPM
4520282632947
Mohsin Kamal5:40‚ÄØPM
4230108855633
Kamran Younus5:41‚ÄØPM
4230122270821
please sir mark my attendance
Fuzail Muzaffar5:42‚ÄØPM
4250181112217
You5:43‚ÄØPM
https://github.com/EnggQasim/NED-batch4-Python/blob/main/class5/OperatorsInPython.ipynb
Ahsan Fayyaz5:43‚ÄØPM
4220115069023
Abdul Haseeb Khan5:44‚ÄØPM
Good suggestion Wajid
upq-oxma-vmi
"""

df5 = attendance(x)
print(len(df5))
df5['c5'] = 1
df5.head()

70

            CNIC  c5
0  4220108354184   1
1  4210105390867   1
2  4220103084339   1
3  4520282632947   1
4  3740680876662   1

In [8]:
x = """
Engr Mahmood Ul Hassan5:24‚ÄØPM
4250185234859
Sadaf Tirmizi5:26‚ÄØPM
42101-7246731-0
Suhail Arif5:28‚ÄØPM
Suhail Arif Hussain  4220176777201
Sadaf Tirmizi5:28‚ÄØPM
4210172457810
Imran Ejaz5:29‚ÄØPM
4200044884823
Ali Mehdi5:29‚ÄØPM
4220193871331
sadia faiyaz5:29‚ÄØPM
4210157421004
Athar Khalid5:30‚ÄØPM
4210158892613
Munir Mirza5:31‚ÄØPM
42101-0575629-9
Rida Batool5:31‚ÄØPM
4210172457810
Ali Jilani5:31‚ÄØPM
4220114056719
Ahmed Ali5:32‚ÄØPM
42101-0724035-9
Ali Nawaz5:35‚ÄØPM
4220157226073
Qureshi Kainat5:36‚ÄØPM
5540124860782
Insharah Khan5:47‚ÄØPM
4210131827012
Hammad Villana5:59‚ÄØPM
4210125481117
4240113406009
ali soorani5:59‚ÄØPM
4210124505207
Hammad Villana6:00‚ÄØPM
3630230577559
muhammad anas6:00‚ÄØPM
4210113165975
Aimen Iftikhar6:00‚ÄØPM
42201 77849728
Misbah Sabir6:07‚ÄØPM
4210158021374
Abdulrafay Memon6:08‚ÄØPM
4520434839071
Farah Asif6:12‚ÄØPM
3740680876662
Noman Younus6:13‚ÄØPM
4220102372205
usama hanif6:14‚ÄØPM
4210132209059
MARYAM RASHID6:21‚ÄØPM
4210198548420
Ahsan Fayyaz6:22‚ÄØPM
4220115069023
Sadiq Fazal6:28‚ÄØPM
42101-7245686-0
Ahsan Fayyaz6:29‚ÄØPM
2 dimensional list
Zeeshan Yaseen6:34‚ÄØPM
4220141892019
wardah siddiqui6:36‚ÄØPM
4210166120772
Muhammad Haneef6:37‚ÄØPM
4220134664875
Sibtain Ahmed6:37‚ÄØPM
4130356133125
dani6:37‚ÄØPM
4250189782769
Ahsan Fayyaz6:40‚ÄØPM
4220115069023
Uzma Habib6:40‚ÄØPM
4520282632947
Fuzail Muzaffar6:43‚ÄØPM
4250181112217
Abdul Haseeb Khan6:43‚ÄØPM
4220103084339
Wajid Khan6:44‚ÄØPM
42101-1693504-9
Ali Affan Yaqoob6:44‚ÄØPM
42101-5031761-9
Ahsan Fayyaz6:45‚ÄØPM
4220115069023
osama saleem6:45‚ÄØPM
4220182861439
M. A. Miher6:45‚ÄØPM
3720117887067
Ali Nawaz6:46‚ÄØPM
4220157226073
Raja Waleed6:46‚ÄØPM
42201-8855051-5
42201-8855051-5    Raja waleed
Abdul Mannan Khan6:50‚ÄØPM
4220143572841
Abdulrafay Memon6:53‚ÄØPM
4520434839071
45204-3483907-1
Misbah Sabir6:54‚ÄØPM
4210158021374
MUHAMMAD AYAZ6:54‚ÄØPM
4520282632947
Nasir Ali6:54‚ÄØPM
4240134843465
MUHAMMAD AYAZ6:56‚ÄØPM
4520282632947
Mohsin Kamal6:56‚ÄØPM
4230108855633
Umer Fariq6:56‚ÄØPM
4220122685447
ali soorani6:56‚ÄØPM
4210124505207
Noor Saba6:56‚ÄØPM
4220187822116
Fahad Aziz Khan6:56‚ÄØPM
4220195795065
Mohsin Kamal6:57‚ÄØPM
4230108855633
Usama Ahmed6:57‚ÄØPM
6110196883915
Ali Nawaz6:57‚ÄØPM
13
Nasir Ali6:57‚ÄØPM
4330401845851
Syed Muzammil Haider6:57‚ÄØPM
4210149039311
wardah siddiqui6:57‚ÄØPM
4210166120772
Mahnoor Arif6:57‚ÄØPM
4220178140796
Insharah Khan6:57‚ÄØPM
4210131827012
Aijaz Ahmed6:57‚ÄØPM
4520691925699
Zubair ,6:57‚ÄØPM
1310104942039
Suhail Arif6:57‚ÄØPM
Suhail Arif Hussain 4220176777201
Raja Waleed6:57‚ÄØPM
42201-8855051-5        Raja waleed
Engr Mahmood Ul Hassan6:57‚ÄØPM
4250185234859
Ali Jilani6:57‚ÄØPM
4220114056719
osama saleem6:57‚ÄØPM
4220182861439
Ali Nawaz6:57‚ÄØPM
4220157226073
SHAHRUKH KHAN6:57‚ÄØPM
4210105390867
Box Brain6:57‚ÄØPM
4130414016931
Farah Asif6:57‚ÄØPM
4220108354184
MUHAMMAD AYAZ6:57‚ÄØPM
MUHAMMAD AYAZ 4520282632947
Abdul Mannan Khan6:57‚ÄØPM
4220143572841
Hassan Qamar6:57‚ÄØPM
4220110629561
Abdulrafay Memon6:57‚ÄØPM
45204-3483907-1
Athar Khalid6:57‚ÄØPM
4210158892613
ehzam ahmed6:57‚ÄØPM
4220176323111
SHAHRUKH KHAN6:57‚ÄØPM
4210129790553
ShahzadAzam Hashmi6:57‚ÄØPM
3630247912847
Dr Nadeem Shah6:57‚ÄØPM
4130464926599
Hassan Saleem6:57‚ÄØPM
4210199525535
Muneeb Bhania6:57‚ÄØPM
4210138182987
4250177756968
Ahtisham Ali Khan6:58‚ÄØPM
3830155517583
Muhammad Haris Bin Khalid6:58‚ÄØPM
4210101244031
MAAZ AHMED6:58‚ÄØPM
4220181749601 attendance
Sheza Shams6:58‚ÄØPM
42201-0218814-0 Sheza
Nasir Ali6:58‚ÄØPM
4230122270821
Sheikh Meraj Uddin6:58‚ÄØPM
4210192333399
Ali Affan Yaqoob6:58‚ÄØPM
42101-5031761-9
Aijaz Ahmed6:59‚ÄØPM
I shared a Jam file with the meeting: https://jamboard.google.com/d/10HPjqI481M0v9w3LO3bPyCdpzUGJ3YV94CN3U_AtLpc/edit?usp=meet_whiteboard
Farah Asif6:59‚ÄØPM
hina hyder 43203-0773876-0
Muhammad Haneef7:00‚ÄØPM
4220134664875
Owais Ahmed7:01‚ÄØPM
4220103194893
upq-oxma-vmi
"""
df6 = attendance(x)
print(len(df6))
df6['c6'] = 1
df6.head()

71

            CNIC  c6
0  4210131827012   1
1  4210105390867   1
2  4220108354184   1
3  4220103084339   1
4  4520282632947   1

In [9]:
x = """
Umair Sajid2:49‚ÄØPM
4220115395943
Suhail Arif2:51‚ÄØPM
voice not clear
Suhail Arif2:52‚ÄØPM
suhail arif hussain 4220176777201
Munir Mirza2:56‚ÄØPM
42101-0575629-9
M. A. Miher2:56‚ÄØPM
3720117887067
Ali Jilani2:56‚ÄØPM
4220114056719
Ali Affan Yaqoob2:57‚ÄØPM
42101-5031761-9
Sadaf Tirmizi2:57‚ÄØPM
42101-7246731-0
sadia faiyaz2:58‚ÄØPM
4210157421004
salman soorani2:58‚ÄØPM
4210124505207
Sibtain Ahmed2:59‚ÄØPM
4130356133125
Uzair Sajjad3:03‚ÄØPM
4210125481117
Abdulrafay Memon3:13‚ÄØPM
45204-3483907-1
4520434839071
Hassan Saleem3:21‚ÄØPM
4210199525535
Abdul Haseeb Khan3:22‚ÄØPM
4220103084339
Athar Khalid3:23‚ÄØPM
4210158892613
Ahmed Ali3:23‚ÄØPM
42101-0724035-9
Engr Mahmood Ul Hassan3:26‚ÄØPM
4250185234859
Ahsan Fayyaz3:26‚ÄØPM
4220115069023
Arsalan Shaikh3:27‚ÄØPM
42201-6205339-3
Owais Ahmed3:29‚ÄØPM
4220103194893
Masood M. Khokhar3:30‚ÄØPM
42501-4808238-9
Ahsan Fayyaz3:31‚ÄØPM
4220115069023
Hina Hyder3:34‚ÄØPM
hina hyder 43203-0773876-0
MARYAM RASHID3:35‚ÄØPM
4210198548420
Ahmed Ali3:35‚ÄØPM
42101-0724035-9
osama saleem3:39‚ÄØPM
4220182861439
Qureshi Kainat3:40‚ÄØPM
5540124860782
Ali Mehdi3:47‚ÄØPM
4220193871331
Misbah Sabir3:49‚ÄØPM
4210158021374
Maria Noor Amjad3:50‚ÄØPM
6110119569820
Fuzail Muzaffar3:56‚ÄØPM
4250181112217
Ayaz Muhammad3:57‚ÄØPM
4520282632947
MAAZ AHMED4:00‚ÄØPM
4220181749601 Attendance
obaid rehman4:01‚ÄØPM
4240113406009
Sadiq Fazal4:01‚ÄØPM
42101-7245686-0
Zeeshan Yaseen4:02‚ÄØPM
4220141892019
Iqra Talha4:04‚ÄØPM
6110120315128
Abdul Mannan Khan4:09‚ÄØPM
4220143572841
Ahsan Fayyaz4:09‚ÄØPM
4220115069023
Muhammad Haneef4:09‚ÄØPM
4220134664875
Imran Ejaz4:09‚ÄØPM
4200044884823
Suhail Arif4:11‚ÄØPM
Suhail Arif Hussain 4220176777201
obaid rehman4:17‚ÄØPM
3630230577559
Munir Mirza4:19‚ÄØPM
4220102372205
Insharah Khan4:24‚ÄØPM
4210131827012
salman soorani4:24‚ÄØPM
4210124505207
ehzam ahmed4:25‚ÄØPM
4220176323111
Aijaz Ahmed4:25‚ÄØPM
4520691925699
Raja Waleed4:27‚ÄØPM
Raja waleed  42201-8855051-5
Abdulrafay Memon4:28‚ÄØPM
4520434839071
Ali Affan Yaqoob4:28‚ÄØPM
4210150317619
Farah Asif4:29‚ÄØPM
37406-8087666-2
usama hanif4:29‚ÄØPM
4210132209059
Mohsin Kamal4:29‚ÄØPM
4230108855633
wardah siddiqui4:30‚ÄØPM
4210166120772
ShahzadAzam Hashmi4:30‚ÄØPM
3630247912847
SHAHRUKH KHAN4:30‚ÄØPM
4210105390867
Muhammad Hasan4:31‚ÄØPM
4240134843465
Dr Nadeem Shah4:33‚ÄØPM
4130464926599
Usama Ahmed4:33‚ÄØPM
6110196883915
Wajid Khan4:33‚ÄØPM
42101-1693504-9
Nasir Ali4:33‚ÄØPM
4240134843465
Muhammad Hasan
Raheel Sadruddin4:33‚ÄØPM
4210129790553
Umer Fariq4:33‚ÄØPM
4220122685447
Nasir Ali4:34‚ÄØPM
4330401845851
Nasir Ali
Mohsin Kamal4:34‚ÄØPM
4230108855633
Fahad Aziz Khan4:34‚ÄØPM
4220195795065
Zubair ,4:34‚ÄØPM
1310104942039
Ayaz Muhammad4:34‚ÄØPM
4520282632947
Muhammad Ayaz
Saad Shoaib4:34‚ÄØPM
41030414016931
Mahnoor Arif4:34‚ÄØPM
4220187822116
Ahtisham Khan4:34‚ÄØPM
3830155517583
Mahnoor Arif4:34‚ÄØPM
4220178140796
Kamran Younus4:34‚ÄØPM
42301-2227082-1
Sibtain Ahmed4:35‚ÄØPM
4130356133125
Muhammad Haris Bin Khalid4:35‚ÄØPM
4210101244031
Arsalan Shaikh4:36‚ÄØPM
42201-6205339-3
Hina Hyder4:37‚ÄØPM
43203-0773876-0...hina hyder
Abdul Mannan Khan4:37‚ÄØPM
4220143572841
Syed Muzammil Haider4:37‚ÄØPM
4210149039311
Aimen Iftikhar4:37‚ÄØPM
42201-7784972-8
Ali Jilani4:37‚ÄØPM
4220114056719
Ali Nawaz4:38‚ÄØPM
4220157226073
Syed Muzammil Haider4:38‚ÄØPM
4210172457810
Abdulrafay Memon4:38‚ÄØPM
45204-3483907-1
Mohsin Kamal4:39‚ÄØPM
4230108855633
osama saleem4:39‚ÄØPM
4220182861439
Muhammad Haris Bin Khalid4:39‚ÄØPM
4210101244031
salman soorani4:39‚ÄØPM
4210124505207
Raja Waleed4:39‚ÄØPM
Raja waleed 42201-8855051-5
Ali Affan Yaqoob4:39‚ÄØPM
4210150317619
Farah Asif4:39‚ÄØPM
37406-8087666-2
upq-oxma-vmi
"""

df7 = attendance(x)
print(len(df7))
df7['c7'] = 1
df7.head()

68

            CNIC  c7
0  4210131827012   1
1  4210105390867   1
2  4220103084339   1
3  4520282632947   1
4  3740680876662   1

In [10]:
x = """
Umair Sajid5:19‚ÄØPM
42201-1539594-3
Munir Mirza5:21‚ÄØPM
42101-0575629-9
M. A. Miher5:21‚ÄØPM
3720117887067
Uzair Sajjad5:23‚ÄØPM
4210125481117
Ahsan Fayyaz5:24‚ÄØPM
4220115069023
Suhail Arif5:25‚ÄØPM
Suhail Arif hussain 4220176777201
Abdul Haseeb Khan5:27‚ÄØPM
4220103084339
Engr Mahmood Ul Hassan5:29‚ÄØPM
4250185234859
Hassan Saleem5:30‚ÄØPM
4210199525535
Uzair Sajjad5:31‚ÄØPM
4140703835369
Owais Ahmed5:33‚ÄØPM
4220103194893
Ahmed Ali5:36‚ÄØPM
42101-0724035-9
Team NED Academy5:37‚ÄØPM
Please start recording  sir
danu5:37‚ÄØPM
4250189782769
Ali Affan Yaqoob5:38‚ÄØPM
42101-5031761-9
Qureshi Kainat5:49‚ÄØPM
5540124860782
Misbah Sabir5:49‚ÄØPM
4210158021374
Imran Ejaz6:08‚ÄØPM
4200044884823
Zaib Batool6:10‚ÄØPM
42101-7245686-0
Iqra Talha6:11‚ÄØPM
6110120315128
Zaib Batool6:11‚ÄØPM
42101-7246731-0
Ahmed Ali6:11‚ÄØPM
42101-0724035-9
Zeeshan Yaseen6:12‚ÄØPM
4220141892019
Ali Jilani6:12‚ÄØPM
4220114056719
Aimen Iftikhar6:12‚ÄØPM
42201-7784972-8
Sibtain Ahmed6:12‚ÄØPM
4130356133125
danu6:13‚ÄØPM
4250189782769
salman soorani6:14‚ÄØPM
4210124505207
Munir Mirza6:14‚ÄØPM
4220102372205
Hassan Qamar6:14‚ÄØPM
4220110629561
Muneeb Bhania6:15‚ÄØPM
4210138182987
Zaib Batool6:16‚ÄØPM
4210157421004
Muneeb Bhania6:16‚ÄØPM
4250177756968
Rida Batool6:21‚ÄØPM
4210172457810
Maria Noor Amjad6:21‚ÄØPM
6110119569820
Insharah Khan6:24‚ÄØPM
4210131827012
Ali Mehdi6:26‚ÄØPM
4220193871331
Fuzail Muzaffar6:34‚ÄØPM
4250181112217
Usama Ahmed6:34‚ÄØPM
6110196883915
ehzam ahmed6:35‚ÄØPM
4220176323111
Muneeb Bhania6:40‚ÄØPM
4250177756968
4210138182987
Hassan Qamar6:41‚ÄØPM
4220110629561
osama saleem6:49‚ÄØPM
4220182861439
Fahad Aziz Khan6:52‚ÄØPM
4220195795065
salman soorani6:52‚ÄØPM
4210124505207
Muhammad Haneef6:52‚ÄØPM
4220134664875
Nasir Ali6:52‚ÄØPM
4330401845851
Ahsan Fayyaz6:52‚ÄØPM
4220115069023
Nasir Ali6:53‚ÄØPM
4240134843465
Hasan
Engr Mahmood Ul Hassan6:53‚ÄØPM
4250185234859
M. A. Miher6:54‚ÄØPM
why should we not find space on both sides of @
Kamran Younus6:54‚ÄØPM
4230122270821
Raja Waleed6:54‚ÄØPM
42201-8855051-5
42201-8855051-5     Raja waleed
Zubair ,7:03‚ÄØPM
1310104942039
Noor Saba7:05‚ÄØPM
4220178140796
4220187822116
muhammad anas7:05‚ÄØPM
4210113165975
Raheel Sadruddin7:06‚ÄØPM
4210129790553
Ali Nawaz7:06‚ÄØPM
4220157226073
salman soorani7:06‚ÄØPM
4210124505207
Abdul Haseeb Khan7:06‚ÄØPM
4220103084339
Abdul Mannan Khan7:06‚ÄØPM
4220143572841
Mohsin Kamal7:06‚ÄØPM
4230108855633
Ahsan Fayyaz7:06‚ÄØPM
4220115069023
osama saleem7:06‚ÄØPM
4220182861439
ehzam ahmed7:06‚ÄØPM
4220176323111
SHAHRUKH KHAN7:06‚ÄØPM
4210105390867
Ahtisham Khan7:06‚ÄØPM
3830155517583
Saad Shoaib7:07‚ÄØPM
413041401416931
MAAZ AHMED7:07‚ÄØPM
4220181749601
Arsalan Shaikh7:07‚ÄØPM
42201-6205339-3
Suhail Arif7:07‚ÄØPM
4210116935049
Syed Muzammil Haider7:07‚ÄØPM
4210149039311
Ali Affan Yaqoob7:07‚ÄØPM
42101-5031761-9
Farah Asif7:07‚ÄØPM
37406-8087666-2
Nasir Ali7:07‚ÄØPM
4240134843465
Hasan
Aijaz Ahmed7:07‚ÄØPM
4520691925699
Umer Fariq7:07‚ÄØPM
4220122685447
Sheza Shams7:07‚ÄØPM
42201-0218814-0
ShahzadAzam Hashmi7:07‚ÄØPM
3630247912847
Nasir Ali7:07‚ÄØPM
4330401845851
Ahmed Ali7:07‚ÄØPM
42101-0724035-9
Zeeshan Yaseen7:08‚ÄØPM
4220141892019
Syed Muzammil Haider7:08‚ÄØPM
4210172457810
Mohsin Kamal7:08‚ÄØPM
4230108855633
Suhail Arif7:08‚ÄØPM
Suhail Arif HUssain 4220176777201
Abdulrafay Memon7:08‚ÄØPM
4520434839071
Muneeb Bhania7:08‚ÄØPM
4250177756968
Suhail Arif7:08‚ÄØPM
4250148082389
Muneeb Bhania7:08‚ÄØPM
4210138182987
usama hanif7:08‚ÄØPM
4210132209059
Saad Shoaib7:09‚ÄØPM
4130414016931
Muhammad Haris Bin Khalid7:10‚ÄØPM
4210101244031
Raja Waleed7:10‚ÄØPM
42201-8855051-5  Raja waleed
Insharah Khan7:10‚ÄØPM
4210131827012
upq-oxma-vmi
"""
df8 = attendance(x)
print(len(df8))
df8['c8'] = 1
df8.head()

68

            CNIC  c8
0  4210131827012   1
1  4210105390867   1
2  4220103084339   1
3  3740680876662   1
4  4520434839071   1

In [11]:
x = """
Sadaf Tirmizi2:48‚ÄØPM
42101-7246731-0
muhammad anas2:53‚ÄØPM
4210113165975
Owais Ahmed2:54‚ÄØPM
4220103194893
osama saleem2:54‚ÄØPM
4220182861439
Ali Affan Yaqoob2:54‚ÄØPM
4210150317619
Uzair Sajjad2:54‚ÄØPM
4210125481117
Sibtain Ahmed2:55‚ÄØPM
4130356133125
Suhail Arif2:55‚ÄØPM
Suhail Arif Hussain 4220176777201
Ahmed Ali2:55‚ÄØPM
42101-0724035-9
M. A. Miher2:55‚ÄØPM
3720117887067
Munir Mirza2:56‚ÄØPM
42101-0575629-9
Athar Khalid2:56‚ÄØPM
4210158892613
Muhammad Haris Bin Khalid2:57‚ÄØPM
4210101244031
sadia faiyaz2:57‚ÄØPM
4210157421004
Misbah Sabir2:58‚ÄØPM
4210158021374
Hassan Qamar3:00‚ÄØPM
4220110629561
Ahsan Fayyaz3:01‚ÄØPM
4220115069023
Zeeshan Yaseen3:01‚ÄØPM
4220141892019
Sadaf Tirmizi3:02‚ÄØPM
4210172457810
Abdul Haseeb Khan3:05‚ÄØPM
4220103084339
Abdulrafay Memon3:06‚ÄØPM
45204-3483907-1
Abdul Mannan Khan3:07‚ÄØPM
4220143572841
Engr Mahmood Ul Hassan3:08‚ÄØPM
4250185234859
Umair Sajid3:11‚ÄØPM
42201-1539594-3
Arsalan Shaikh3:15‚ÄØPM
42201-6205339-3
Iqra Talha3:17‚ÄØPM
61101-2031512-8
obaid rehman3:19‚ÄØPM
4240113406009
Imran Ejaz3:19‚ÄØPM
4200044884823
Masood M. Khokhar3:19‚ÄØPM
4250148082389
Farooq Ahmad3:19‚ÄØPM
3520294446451
Munir Mirza3:21‚ÄØPM
4220102372205
Sheikh Meraj Uddin3:25‚ÄØPM
4210192333399
Wajid Khan3:27‚ÄØPM
4210116935049
salman soorani3:37‚ÄØPM
4210124505207
Hassan Saleem3:40‚ÄØPM
4210199525535
Abdulrafay Memon3:40‚ÄØPM
4520434839071
Sadiq Fazal3:41‚ÄØPM
42101-7245686-0
Ahsan Fayyaz3:45‚ÄØPM
4220115069023
wardah siddiqui3:46‚ÄØPM
4210166120772
Ali Mehdi3:46‚ÄØPM
4220193871331
Insharah Khan3:50‚ÄØPM
4210131827012
ShahzadAzam Hashmi3:50‚ÄØPM
3630247912847
SHAHRUKH KHAN3:51‚ÄØPM
4210105390867
Daniyal3:58‚ÄØPM
4250189782769
ehzam ahmed4:04‚ÄØPM
4220176323111
Aijaz Ahmed4:04‚ÄØPM
please give a recap of loop
Muhammad Haneef4:06‚ÄØPM
4220134664875
Fahad Aziz Khan4:09‚ÄØPM
4220195795065
Ahmed Ali4:14‚ÄØPM
42101-0724035-9
NASIR ALI4:15‚ÄØPM
4330401845851
Maria Noor Amjad4:16‚ÄØPM
6110119569820
salman soorani4:17‚ÄØPM
4210124505207
Aijaz Ahmed4:17‚ÄØPM
4520691925699
Mohsin Kamal4:17‚ÄØPM
4230108855633
Abdulrafay Memon4:17‚ÄØPM
4520434839071
Umer Fariq4:17‚ÄØPM
4220122685447
Farooq Ahmad4:17‚ÄØPM
3520294446451
Ali Jilani4:17‚ÄØPM
4220114056719
MAAZ AHMED4:17‚ÄØPM
4220181749601 attendance
Ahtisham Khan4:17‚ÄØPM
3830155517583
Engr Mahmood Ul Hassan4:17‚ÄØPM
4250185234859
Suhail Arif4:17‚ÄØPM
422017677720
Mahnoor Arif4:17‚ÄØPM
4420178140796
Farah Asif4:17‚ÄØPM
3740680876662
Saad Shoaib4:17‚ÄØPM
41304-1401693-1
Arsalan Shaikh4:17‚ÄØPM
42201-6205339-3
Masood M. Khokhar4:17‚ÄØPM
4250148082389
usama hanif4:17‚ÄØPM
4210132209059
Kamran Younus4:17‚ÄØPM
42301-2227082-1
Noor Saba4:17‚ÄØPM
4220187822116
Dr Nadeem Shah4:18‚ÄØPM
4130464926599
Muhammad Haris Bin Khalid4:18‚ÄØPM
4210101244031
Mohsin Kamal4:18‚ÄØPM
4230108855633
Zubair ,4:18‚ÄØPM
1310104942039
Raheel Sadruddin4:18‚ÄØPM
4210129790553
Ali Affan Yaqoob4:19‚ÄØPM
4210150317619
osama saleem4:19‚ÄØPM
4220182861439
Sheza Shams4:19‚ÄØPM
42201-0218814-0
Aijaz Ahmed4:20‚ÄØPM
plan midterm another day
Abdul Mannan Khan4:21‚ÄØPM
4220143572841
Mohsin Kamal4:21‚ÄØPM
4230108855633
upq-oxma-vmi
"""
df9 = attendance(x)
print(len(df9))
df9['c9'] = 1
df9.head()

63

            CNIC  c9
0  4210131827012   1
1  4210105390867   1
2  4220103084339   1
3  3740680876662   1
4  4520434839071   1

In [12]:
x = """
Owais Ahmed5:18‚ÄØPM
4220103194893
Ali Jilani5:18‚ÄØPM
4220114056719
Ali Affan Yaqoob5:19‚ÄØPM
42101-5031761-9
Sibtain Ahmed5:19‚ÄØPM
4130356133125
Imran Ejaz5:19‚ÄØPM
4200044884823
Ahsan Fayyaz5:27‚ÄØPM
4220115069023
4220115069023
Suhail Arif5:28‚ÄØPM
Suhail Arif Hussain 4220176777201
MAAZ AHMED5:29‚ÄØPM
Attendance 4220181749601
MAAZ AHMED5:31‚ÄØPM
noise in AUDIO
Munir Mirza5:32‚ÄØPM
42101-0575629-9
Ahmed Ali5:32‚ÄØPM
42101-0724035-9
Muhammad Haris Bin Khalid5:33‚ÄØPM
4210101244031
ShahzadAzam Hashmi5:33‚ÄØPM
3630247912847
Abdul Haseeb Khan5:44‚ÄØPM
4220103084339
Maria Noor Amjad5:48‚ÄØPM
6110119569820
Munir Mirza5:49‚ÄØPM
4220102372205
Hassan Qamar5:58‚ÄØPM
4220110629561
Abdulrafay Memon5:59‚ÄØPM
4520434839071
salman soorani6:09‚ÄØPM
4210124505207
Zeeshan Yaseen6:09‚ÄØPM
4220141892019
wardah siddiqui6:10‚ÄØPM
4210166120772
usama hanif6:12‚ÄØPM
4210132209059
Qureshi Kainat6:15‚ÄØPM
5540124860782
Insharah Khan6:16‚ÄØPM
4210131827012
Ali Mehdi6:16‚ÄØPM
4220193871331
MARYAM RASHID6:19‚ÄØPM
4210198548420
Noor Saba6:20‚ÄØPM
4220187822116
4220178140796
Ahsan Fayyaz6:21‚ÄØPM
4220115069023
Ahtisham Khan6:21‚ÄØPM
3831055517583
Ali Nawaz6:21‚ÄØPM
4220157226073
sadia faiyaz6:24‚ÄØPM
4210157421004
Engr Mahmood Ul Hassan6:24‚ÄØPM
4250185234859
Wajid Khan6:28‚ÄØPM
4210116935049
sadia faiyaz6:29‚ÄØPM
4220108354184
Muneeb Bhania6:33‚ÄØPM
4210138182987
Daniyal6:33‚ÄØPM
4250189782769
Aijaz Ahmed6:33‚ÄØPM
4520691925699
ehzam ahmed6:36‚ÄØPM
4220176323111
Zeeshan Yaseen6:37‚ÄØPM
4220141892019
Muhammad Uzair6:48‚ÄØPM
4210125481117
3630230577559
SHAHRUKH KHAN6:49‚ÄØPM
4210105390867
Muhammad Uzair6:49‚ÄØPM
4240113406009
NASIR ALI6:50‚ÄØPM
4330401845851
Ali Nawaz6:50‚ÄØPM
4220157226073
Kamran Younus6:51‚ÄØPM
42301-2227082-1
Rida Batool6:51‚ÄØPM
4210172457810
Rida Batool6:52‚ÄØPM
4210172467310
muhammad anas6:54‚ÄØPM
4210113165975
Waleed Ahmed Siddiqui6:54‚ÄØPM
4210195297779
Fahad Aziz Khan6:54‚ÄØPM
4220195795061
Imran Ejaz6:55‚ÄØPM
4200044884823
Sheza Shams6:56‚ÄØPM
42201-0218814-0
Farooq Ahmad6:56‚ÄØPM
3520294446451
salman soorani6:56‚ÄØPM
4210124505207
Muneeb Bhania6:56‚ÄØPM
42101-3818298-7
Mohsin Kamal6:56‚ÄØPM
4230108855633
Raheel Sadruddin6:56‚ÄØPM
4210129790553
Ahtisham Khan6:56‚ÄØPM
3830155517583
Syed Muzammil Haider6:56‚ÄØPM
4210149039311
Ifra Siddiqui6:56‚ÄØPM
4250177756968
Umer Fariq6:56‚ÄØPM
4220122685447
Ahmed Ali6:56‚ÄØPM
42101-0724035-9
Zubair ,6:56‚ÄØPM
1310104942039
Ali Affan Yaqoob6:56‚ÄØPM
42101-5031761-9
Ahsan Fayyaz6:56‚ÄØPM
4220115069023
Mohsin Kamal6:56‚ÄØPM
4230108855633
ShahzadAzam Hashmi6:56‚ÄØPM
3630247912847
Sibtain Ahmed6:56‚ÄØPM
4130356133125
Abdulrafay Memon6:56‚ÄØPM
45204-3483907-1
Dr Nadeem Shah6:56‚ÄØPM
4130464926599
Engr Mahmood Ul Hassan6:56‚ÄØPM
4250185234859
Abdul Haseeb Khan6:56‚ÄØPM
4220103084339
Mohsin Kamal6:56‚ÄØPM
4230108855633
Farah Asif6:56‚ÄØPM
37406-8087666-2
Suhail Arif6:57‚ÄØPM
Suhail Arif Hussain 4220176777201
Ahsan Fayyaz6:57‚ÄØPM
4220115069023
Abdulrafay Memon6:57‚ÄØPM
4520434839071
Abdul Mannan Khan6:57‚ÄØPM
4220143572841
Ali Mehdi6:57‚ÄØPM
4220193871331
Misbah Sabir6:57‚ÄØPM
4210158021374
Muhammad Haris Bin Khalid6:57‚ÄØPM
4210101244031
Owais Ahmed6:57‚ÄØPM
4220103194893
Athar Khalid6:57‚ÄØPM
4210158892613
osama saleem6:57‚ÄØPM
4220182861439
MARYAM RASHID6:57‚ÄØPM
4210198548420
Raja Waleed6:57‚ÄØPM
4220188550515
Sheikh Meraj Uddin6:57‚ÄØPM
4210192333399
Qureshi Kainat6:57‚ÄØPM
5540124860782
Athar Khalid6:57‚ÄØPM
4250148082389
MAAZ AHMED6:57‚ÄØPM
4220181749601
Athar Khalid6:57‚ÄØPM
4210132209059
4220162053393
wardah siddiqui6:58‚ÄØPM
4210166120772
upq-oxma-vmi
"""
df10 = attendance(x)
print(len(df10))
df10['c10'] = 1
df10.head()

67

            CNIC  c10
0  4210131827012    1
1  4220108354184    1
2  4210105390867    1
3  4220103084339    1
4  3740680876662    1

In [13]:
x = """
Athar Khalid2:48‚ÄØPM
4210158892613
Sibtain Ahmed2:49‚ÄØPM
4130356133125
Muhammad Haneef2:50‚ÄØPM
4220134664875
M. A. Miher2:50‚ÄØPM
3720117887067
Aimen Iftikhar2:51‚ÄØPM
42201 77849728
Suhail Arif2:51‚ÄØPM
Suhail Arif Hussain 4220176777201
Mahnoor Arif2:52‚ÄØPM
42201-7814079-6
Engr Mahmood Ul Hassan2:57‚ÄØPM
4250185234859
Uzair Sajjad2:58‚ÄØPM
42101-2548111-7
Marium Imran2:59‚ÄØPM
4200044884823
MAAZ AHMED3:03‚ÄØPM
4220181749601 attendance
Munir Mirza3:07‚ÄØPM
42101-0575629-9
Ali Affan Yaqoob3:07‚ÄØPM
42101-5031761-9
Insharah Khan3:08‚ÄØPM
4210131827012
Sadaf Tirmizi3:09‚ÄØPM
4210172467310
salman soorani3:09‚ÄØPM
4210124505207
Ahmed Ali3:10‚ÄØPM
42101-0724035-9
Owais Ahmed3:10‚ÄØPM
4220103194893
Qureshi Kainat3:12‚ÄØPM
5540134860782
5540124860782
Dr Nadeem Shah3:12‚ÄØPM
4130464926599
Maria Noor Amjad3:21‚ÄØPM
6110119569820
osama saleem3:22‚ÄØPM
4220182861439
sadia faiyaz3:22‚ÄØPM
4210157421004
Masood M. Khokhar3:26‚ÄØPM
4250148082389
Masood Mehmood Khokhar
ShahzadAzam Hashmi3:27‚ÄØPM
3630247912847
Aijaz Ahmed3:27‚ÄØPM
4520691925699
muhammad anas3:39‚ÄØPM
4210113165975
Ali Nawaz3:41‚ÄØPM
42201-5722607-3
Daniyal3:41‚ÄØPM
4250189782769
Abdul Haseeb Khan3:44‚ÄØPM
4220103084339
Hassan Qamar3:45‚ÄØPM
4220110629561
Sheikh Meraj Uddin3:45‚ÄØPM
4210192333399
Ali Mehdi3:47‚ÄØPM
4220193871331
Abdulrafay Memon3:58‚ÄØPM
45204-3483907-1
4520434839071
usama hanif3:59‚ÄØPM
4210132209059
Sadiq Fazal3:59‚ÄØPM
42101-7245686-0
NASIR ALI3:59‚ÄØPM
4330301845851
4330401845851
Ayaz Muhammad4:04‚ÄØPM
4520282632947
Abdulrafay Memon4:13‚ÄØPM
45204-3483907-1
MAAZ AHMED4:18‚ÄØPM
https://youtu.be/ORIrSFWyYvM
Areeba Ghazal4:18‚ÄØPM
4220108354184
areeba ghazal
Muhammad Ali4:23‚ÄØPM
4220114056719
Hafiz Abdul Wahid Khan4:23‚ÄØPM
4210116935049
amir sohail4:23‚ÄØPM
4140703835369
Fahad Aziz Khan4:23‚ÄØPM
4220195795065
Suhail Arif4:24‚ÄØPM
Suhail Arif HUssain 4220176777201
Rameez Shaikh4:25‚ÄØPM
Sheikh Muhammad Rameez 4210149117409
Munir Mirza4:28‚ÄØPM
4220103372205
Aijaz Ahmed4:28‚ÄØPM
4520691925699
SHAHRUKH KHAN4:28‚ÄØPM
4210105390867
ehzam ahmed4:29‚ÄØPM
4220176323111
Muneeb Bhania4:29‚ÄØPM
42101-3818298-7
Umer Fariq4:31‚ÄØPM
4220122685447
wardah siddiqui4:31‚ÄØPM
4210166120772
Abdul Mannan Khan4:31‚ÄØPM
4220143572841
Noor Saba4:32‚ÄØPM
4220187822116
Ahmed Ali4:32‚ÄØPM
42101-0724035-9
Muhammad Haris Bin Khalid4:33‚ÄØPM
4210101244031
Iqra Talha4:34‚ÄØPM
61101-2031512-8
Abdul Haseeb Khan4:35‚ÄØPM
4220103084339
Mohsin Kamal4:40‚ÄØPM
4230108855633
Ifra Siddiqui4:41‚ÄØPM
4250177756968
salman soorani4:43‚ÄØPM
4210124505207
Marium Imran4:43‚ÄØPM
4200044884823
Dr Nadeem Shah4:43‚ÄØPM
4130464926599
Sheza Shams4:44‚ÄØPM
42201-0218814-0
Mohsin Kamal4:44‚ÄØPM
4230108855633
Usama Ahmed4:44‚ÄØPM
6110196883915
Abdul Mannan Khan4:44‚ÄØPM
4220143572841
Raja Waleed4:44‚ÄØPM
42201-8855051-5    Raja waleed
Farah Asif4:44‚ÄØPM
37406-8087666-2
Raheel Sadruddin4:44‚ÄØPM
4210129790553
Ali Affan Yaqoob4:44‚ÄØPM
4210150317619
Mahnoor Arif4:44‚ÄØPM
4220178140796
Zubair ,4:44‚ÄØPM
1310104942039
Ayaz Muhammad4:44‚ÄØPM
4520282632947
MAAZ AHMED4:44‚ÄØPM
4220181749601
Ahtisham Khan4:44‚ÄØPM
3830155517583
Masood M. Khokhar4:44‚ÄØPM
4250148082389
Ahmed Ali4:44‚ÄØPM
42101-0724035-9
wardah siddiqui4:44‚ÄØPM
4210166120772
ShahzadAzam Hashmi4:44‚ÄØPM
3630247912847
Muneeb Bhania4:44‚ÄØPM
4210138182987
Syed Muzammil Haider4:44‚ÄØPM
4210149039311
Arsalan Shaikh4:44‚ÄØPM
42201-6505339-3
Muhammad Haneef4:44‚ÄØPM
4220134664875
Ifra Siddiqui4:44‚ÄØPM
4250177756968
osama saleem4:44‚ÄØPM
4220182861439
Farooq Ahmad4:44‚ÄØPM
3520294446451
upq-oxma-vmi
"""

df11 = attendance(x)
print(len(df11))
df11['c11'] = 1
df11.head()

67

            CNIC  c11
0  5540134860782    1
1  4210131827012    1
2  4220108354184    1
3  4210105390867    1
4  4220103084339    1

In [14]:
x = """
Abdul Haseeb Khan3:27‚ÄØPM
4220103084339
osama saleem3:30‚ÄØPM
4220182861439
Abdulrafay Memon3:30‚ÄØPM
45204-3483907-1
salman soorani3:30‚ÄØPM
4210124505207
Hassan Saleem3:30‚ÄØPM
4210199525535
Ali Affan Yaqoob3:30‚ÄØPM
42101-5031761-9
Hassan Qamar3:34‚ÄØPM
4220110629561
Sadaf Tirmizi3:39‚ÄØPM
42101-7246731-0
sadia faiyaz3:41‚ÄØPM
4210157421004
Ayaz Muhammad3:43‚ÄØPM
4520282632947
Usama Ahmed3:43‚ÄØPM
6110196883915
amir sohail3:44‚ÄØPM
4140703835369
Ali Mehdi3:47‚ÄØPM
4220193871331
Masood M. Khokhar3:48‚ÄØPM
4250148082389
Owais Ahmed3:49‚ÄØPM
4220103194893
Misbah Sabir3:49‚ÄØPM
4210158021374
Dr Nadeem Shah3:50‚ÄØPM
4130464926599
Ahsan Fayyaz4:02‚ÄØPM
4220115069023
sadia faiyaz4:07‚ÄØPM
4210157421004
Suhail Arif4:10‚ÄØPM
suhail arif hussain 4220176777201
Ayaz Muhammad4:10‚ÄØPM
4520282632947
Abdulrafay Memon4:12‚ÄØPM
4520434839071\
4520434839071
Fuzail Muzaffar4:14‚ÄØPM
4250181112217
Ali Affan Yaqoob4:14‚ÄØPM
42101-5031761-9
usama hanif4:15‚ÄØPM
4210132209059
Ahmed Ali4:15‚ÄØPM
42101-0724035-9
Ahsan Fayyaz4:17‚ÄØPM
4220115069023
Daniyal4:17‚ÄØPM
4250189782769
Imran Ejaz4:18‚ÄØPM
4200044884823
wardah siddiqui4:21‚ÄØPM
4210166120772
Abdul Haseeb Khan4:21‚ÄØPM
4220103084339
Sheikh Meraj Uddin4:24‚ÄØPM
4210192333399
salman soorani4:24‚ÄØPM
4210124505207
Sheza Shams4:26‚ÄØPM
42201-0218814-0    Sheza
Abdul Haseeb Khan4:26‚ÄØPM
4220103084339
SHAHRUKH KHAN4:27‚ÄØPM
4210105390867
muhammad anas4:30‚ÄØPM
4210113165975
Raja Waleed4:34‚ÄØPM
42201-8855051-5
MAAZ AHMED4:34‚ÄØPM
42201-8174960-1 ATTENDANCE
Zubair ,4:36‚ÄØPM
1310104942039
Usama Ahmed4:41‚ÄØPM
6110196883915
Masood M. Khokhar4:42‚ÄØPM
4250148082389
Engr Mahmood Ul Hassan4:43‚ÄØPM
4250185234859
Saad Shoaib4:44‚ÄØPM
4130414016931
Abdulrafay Memon4:44‚ÄØPM
4520434839071
Farah Asif4:45‚ÄØPM
37406-8087666-2
ehzam ahmed4:45‚ÄØPM
4220176323111
Kamran Younus4:45‚ÄØPM
42301-2227082-1
salman soorani4:45‚ÄØPM
4210124505207
Raheel Sadruddin4:45‚ÄØPM
42101297905553
Mohsin Kamal4:45‚ÄØPM
4230108855633
Farooq Ahmad4:45‚ÄØPM
3520294446451
Raheel Sadruddin4:46‚ÄØPM
4210129790553
Ifra Siddiqui4:46‚ÄØPM
4250177756968
Syed Muzammil Haider4:46‚ÄØPM
4210149039311
Aijaz Ahmed4:46‚ÄØPM
4520691925699
Mahnoor Arif4:46‚ÄØPM
422017814796
Arsalan Shaikh4:46‚ÄØPM
42201-6205339-3
Muhammad Ali4:46‚ÄØPM
4220114056719
Umer Fariq4:46‚ÄØPM
4220122685447
Saad Shoaib4:46‚ÄØPM
4130414016931
Ali Affan Yaqoob4:46‚ÄØPM
4210150317619
Abdul Haseeb Khan4:46‚ÄØPM
4220103084339
ShahzadAzam Hashmi4:46‚ÄØPM
3630247912847
Suhail Arif4:46‚ÄØPM
suhail arif 4220176777201
Muhammad Haris Bin Khalid4:47‚ÄØPM
4210101244031
wardah siddiqui4:47‚ÄØPM
4210166120772
osama saleem4:47‚ÄØPM
4220182861439
Dr Nadeem Shah4:47‚ÄØPM
4130464926599
Imran Ejaz4:48‚ÄØPM
4200044884823
Ali Affan Yaqoob4:48‚ÄØPM
42101-5031761-9
Iqra Talha4:48‚ÄØPM
6110120315128
usama hanif4:48‚ÄØPM
4210132209059
upq-oxma-vmi
"""


df12 = attendance(x)
print(len(df12))
df12['c12'] = 1
df12.head()

49

            CNIC  c12
0  4210105390867    1
1  4220103084339    1
2  4520282632947    1
3  3740680876662    1
4  4520434839071    1

In [15]:
x = """
Ahsan Fayyaz5:15‚ÄØPM
4220115069023
Sadaf Tirmizi5:16‚ÄØPM
42101-7246731-0
Misbah Sabir5:17‚ÄØPM
4210158021374
Ali Nawaz5:22‚ÄØPM
4220157226073
amir sohail5:22‚ÄØPM
4140703835369
Munir Mirza5:22‚ÄØPM
42101-0575629-9
Muhammad Uzair5:23‚ÄØPM
4210125481117
Suhail Arif5:27‚ÄØPM
suhail arif hussain 4220176777201
Raheel Sadruddin5:28‚ÄØPM
object-oriented programing
Noman Younus5:32‚ÄØPM
4220102372205
Umer Fariq5:33‚ÄØPM
4220122685447
Hassan Qamar5:34‚ÄØPM
4220110629561
Engr Mahmood Ul Hassan5:34‚ÄØPM
4250185234859
Sheikh Meraj Uddin5:34‚ÄØPM
4210192333399
Ahsan Fayyaz5:34‚ÄØPM
4220182861439
Ali Affan Yaqoob5:35‚ÄØPM
42101-5031761-9
Imran Ejaz5:36‚ÄØPM
4200044884823
Owais Ahmed5:36‚ÄØPM
4220103194893
Farooq Ahmad5:46‚ÄØPM
Voice?
Ayaz Muhammad5:46‚ÄØPM
4520282632947
salman soorani5:47‚ÄØPM
4210124505207
sadia faiyaz5:48‚ÄØPM
4210157421004
muhammad anas5:50‚ÄØPM
4210113165975
ShahzadAzam Hashmi5:51‚ÄØPM
3630247912847
Abdulrafay Memon5:51‚ÄØPM
45204-3483907-1
Aijaz Ahmed6:02‚ÄØPM
4520691925699
salman soorani6:05‚ÄØPM
4210124505207
Mohsin Kamal6:09‚ÄØPM
4230108855633
Maria Noor Amjad6:13‚ÄØPM
6110119569820
Ahsan Fayyaz6:14‚ÄØPM
4220115069023
Masood M. Khokhar6:16‚ÄØPM
4250148082389
Mohsin Kamal6:17‚ÄØPM
4230108855633
Ali Mehdi6:17‚ÄØPM
4220193871331
Mohsin Kamal6:17‚ÄØPM
4210116935049
Ahmed Ali6:23‚ÄØPM
42101-0724035-9
Fahad Aziz Khan6:24‚ÄØPM
4220195795065
Noman Younus6:28‚ÄØPM
4220102372205
salman soorani6:29‚ÄØPM
4210124505207
Usama Ahmed6:29‚ÄØPM
6110196883915
Zubair ,6:29‚ÄØPM
1310104942039
Daniyal6:29‚ÄØPM
4250189782769
Dr Nadeem Shah6:30‚ÄØPM
4130464926599
Abdulrafay Memon6:30‚ÄØPM
4520434839071
Ifra Siddiqui6:30‚ÄØPM
4250177756968
4210138182987
Noor Saba6:31‚ÄØPM
4220187822116
usama hanif6:31‚ÄØPM
4210132209059
Ali Jilani6:31‚ÄØPM
4220114056719
Iqra Talha6:32‚ÄØPM
6110120315128
Misbah Sabir6:32‚ÄØPM
mic mute krade sir
double awaz arae
Ali Affan Yaqoob6:35‚ÄØPM
42101-5031761-9
salman soorani6:36‚ÄØPM
4210124505207
wardah siddiqui6:37‚ÄØPM
4210166120772
Kamran Younus6:37‚ÄØPM
42301-2227082-1
Ahsan Fayyaz6:37‚ÄØPM
4220115069023
Ayaz Muhammad6:39‚ÄØPM
4520282632947
Farooq Ahmad6:39‚ÄØPM
3520294446451
Mahnoor Arif6:49‚ÄØPM
4220178140796
SHAHRUKH KHAN6:50‚ÄØPM
4210105390867
salman soorani6:50‚ÄØPM
4210124505207
salman soorani6:51‚ÄØPM
I shared a Jam file with the meeting: https://jamboard.google.com/d/1Pt3uFweqe4uPDULAWTsBczx3uElckLeFQkaawaQff_E/edit?usp=meet_whiteboard
ehzam ahmed6:52‚ÄØPM
4220176323111
salman soorani6:54‚ÄØPM
4210124505207
Ifra Siddiqui6:54‚ÄØPM
4250177756968
Raheel Sadruddin6:54‚ÄØPM
4210129790553
Abdulrafay Memon6:54‚ÄØPM
4520434839071
Ahsan Fayyaz6:54‚ÄØPM
4220115069023
Dr Nadeem Shah6:54‚ÄØPM
4130464926599
Zubair ,6:54‚ÄØPM
3720117887067
Ali Affan Yaqoob6:54‚ÄØPM
42101-5031761-9
Engr Mahmood Ul Hassan6:54‚ÄØPM
4250185234859
Ifra Siddiqui6:54‚ÄØPM
4210138182987
ShahzadAzam Hashmi6:54‚ÄØPM
3630247912847
Masood M. Khokhar6:54‚ÄØPM
42501-4808238-9
Abdul Haseeb Khan6:54‚ÄØPM
4220103084339
Daniyal6:54‚ÄØPM
4250189782769
sadia faiyaz6:54‚ÄØPM
4210157421004
Dr Nadeem Shah6:54‚ÄØPM
4130464926599
Sheza Shams6:54‚ÄØPM
42201-0218814-0
upq-oxma-vmi
"""
df13 = attendance(x)
print(len(df13))
df13['c13'] = 1
df13.head()

51

            CNIC  c13
0  4210105390867    1
1  4220103084339    1
2  4520282632947    1
3  4520434839071    1
4  4220122685447    1

In [16]:
x = """
Suhail Arif2:46‚ÄØPM
ess sir
M. A. Miher2:51‚ÄØPM
3720117887067
Abdul Mannan Khan2:51‚ÄØPM
4220143572841
Imran Karim2:51‚ÄØPM
4210103758455
Engr Mahmood Ul Hassan2:51‚ÄØPM
4250185234859
osama saleem2:52‚ÄØPM
4220182861439
Arsalan Shaikh2:52‚ÄØPM
42201-6205339-3
MAAZ AHMED2:52‚ÄØPM
Attendance
4220181749601
Suhail Arif2:52‚ÄØPM
suhail arif 4220176777201
Sadaf Tirmizi2:54‚ÄØPM
42101-7246731-0
Misbah Sabir2:54‚ÄØPM
42101-5802137-4
Ali Jilani2:55‚ÄØPM
4220114056719
Saad Shoaib2:56‚ÄØPM
41304-1401693-1
Munir Mirza2:57‚ÄØPM
42101-0575629-9
Wahid Khan2:58‚ÄØPM
4210116935049
amir sohail2:58‚ÄØPM
4140703835369
Owais Ahmed2:58‚ÄØPM
4220103194893
Masood M. Khokhar2:59‚ÄØPM
42501-4808238-9
Umer Fariq3:03‚ÄØPM
4220122685447
Masood M. Khokhar3:04‚ÄØPM
42501-4808238-9
Uzair Sajjad3:07‚ÄØPM
4210125481117
muhammad anas3:07‚ÄØPM
4210113165975
Zeeshan Yaseen3:08‚ÄØPM
4220141892019
Ali Affan Yaqoob3:11‚ÄØPM
42101-5031761-9
sadia faiyaz3:12‚ÄØPM
4210157421004
Munir Mirza3:12‚ÄØPM
4220102372205
ShahzadAzam Hashmi3:13‚ÄØPM
3630247912847
Ahmed Ali3:15‚ÄØPM
42101-0724035-9
Hassan Saleem3:15‚ÄØPM
4210199525535
Fahad Aziz Khan3:18‚ÄØPM
4220195795065
Owais Ahmed3:20‚ÄØPM
4220103194893
Dr Nadeem Shah3:20‚ÄØPM
4130464926599
wardah siddiqui3:28‚ÄØPM
4210166120772
salman soorani3:29‚ÄØPM
4210124505207
Athar Khalid3:32‚ÄØPM
4210158892613
Maria Noor Amjad3:40‚ÄØPM
6110119569820
Sadiq Fazal3:41‚ÄØPM
42101-7245686-0
Suhail Arif3:41‚ÄØPM
suhail arif 42201767772201
Aijaz Ahmed3:45‚ÄØPM
4520691925699
Ali Mehdi3:53‚ÄØPM
4220193871331
MARYAM RASHID3:53‚ÄØPM
4210198548420
Iqra Talha3:53‚ÄØPM
6110120315128
ShahzadAzam Hashmi3:54‚ÄØPM
3630247912847
Mahnoor Arif3:55‚ÄØPM
4220187822116
Abdul Mannan Khan4:01‚ÄØPM
4220143572841
Zubair ,4:14‚ÄØPM
1310104942039
Hassan Saleem4:15‚ÄØPM
4210199525535
Farah Asif4:16‚ÄØPM
37406-8087666-2
wardah siddiqui4:19‚ÄØPM
4210166120772
Sheza Shams4:22‚ÄØPM
42201-0218814-0
Ali Affan Yaqoob4:23‚ÄØPM
42101-5031761-9
Kamran Younus4:23‚ÄØPM
42301-2227082-1
Hassan Qamar4:24‚ÄØPM
4220110629561
SHAHRUKH KHAN4:24‚ÄØPM
4210105390867
Raheel Sadruddin4:25‚ÄØPM
4210129790553
Engr Mahmood Ul Hassan4:26‚ÄØPM
http://estirj.com/vol2iss2.htm
Daniyal4:27‚ÄØPM
4250189782769
Ahsan Fayyaz4:28‚ÄØPM
4220115069023
Mohsin Kamal4:35‚ÄØPM
4230108855633
Imran Karim4:36‚ÄØPM
yes sir
salman soorani4:36‚ÄØPM
4210124505207
ahmed ali4:36‚ÄØPM
42101-0724035-9
Farooq Ahmad4:36‚ÄØPM
3520294446451
ehzam ahmed4:36‚ÄØPM
4220176323111
Usama Ahmed4:36‚ÄØPM
6110196883915
Mahnoor Arif4:36‚ÄØPM
4220178140796
Raheel Sadruddin4:36‚ÄØPM
4210129790553
osama saleem4:36‚ÄØPM
4220182861439
Ahsan Fayyaz4:36‚ÄØPM
4220115069023
usama hanif4:36‚ÄØPM
4210132209059
sadia faiyaz4:36‚ÄØPM
4210157421004
Ali Jilani4:36‚ÄØPM
4220114056719
Saad Shoaib4:36‚ÄØPM
4130414016931
Suhail Arif4:37‚ÄØPM
suhail arif hussain 4220176777201
upq-oxma-vmi
"""

df14= attendance(x)
print(len(df14))
df14['c14'] = 1
df14.head()

54

            CNIC  c14
0  4210105390867    1
1  3740680876662    1
2  4130414016931    1
3  4220122685447    1
4  4210172456860    1

In [17]:
x = """
Suhail Arif5:10‚ÄØPM
Suhail Arfu Hussain 4220176777201
Munir Mirza5:18‚ÄØPM
42101-0575629-9
Masood M. Khokhar5:19‚ÄØPM
42501-4808238-9
Wahid Khan5:19‚ÄØPM
4210116935049
M. A. Miher5:20‚ÄØPM
3720117887067
Sadaf Tirmizi5:20‚ÄØPM
4210172467310
Hassan Qamar5:23‚ÄØPM
4220110629561
Uzair Sajjad5:24‚ÄØPM
4210125481117
MARYAM RASHID5:25‚ÄØPM
4210198548420
Sir bht distortion arhi hy
Muhammad Haris Bin Khalid5:30‚ÄØPM
4210101244031
Rubina Aslam5:30‚ÄØPM
4210105390867
salman soorani5:36‚ÄØPM
4210124505207
Athar Khalid5:36‚ÄØPM
4210158892613
There is some disturbing noice
Dr Nadeem Shah5:37‚ÄØPM
4130464926599
Munir Mirza5:40‚ÄØPM
4220102372205
Engr Mahmood Ul Hassan5:41‚ÄØPM
4250185234859
ShahzadAzam Hashmi5:45‚ÄØPM
3630247912847
Fahad Aziz Khan5:50‚ÄØPM
4220195795065
Noor Saba5:58‚ÄØPM
4220178140496
Dr Nadeem Shah5:58‚ÄØPM
4130464926599
Misbah Sabir5:59‚ÄØPM
42101-5802137-4
sadia faiyaz6:00‚ÄØPM
4210157421004
Hassan Saleem6:00‚ÄØPM
4210199525535
Ayaz Muhammad6:02‚ÄØPM
4520282632947
Owais Ahmed6:05‚ÄØPM
4220103194893
Raja Waleed6:05‚ÄØPM
42201-8855051-5
Ahmed Ali6:05‚ÄØPM
42101-0724035-9
Noor Saba6:05‚ÄØPM
4220187822116
You6:12‚ÄØPM
https://www.youtube.com/channel/UCml65rMhaWnwyg4dW2m5hEg
Zeeshan Yaseen6:14‚ÄØPM
4220141892019
Maria Noor Amjad6:16‚ÄØPM
6110119569820
Ali Affan Yaqoob6:19‚ÄØPM
42101-5031761-9
wardah siddiqui6:22‚ÄØPM
4210166120772
sadia faiyaz6:24‚ÄØPM
4210157421004
Zubair ,6:25‚ÄØPM
1310104942039
MAAZ AHMED6:25‚ÄØPM
NO AUDIO?
Ali Jilani6:26‚ÄØPM
4220114056719
Fuzail Muzaffar6:26‚ÄØPM
4250181112217
Sadiq Fazal6:26‚ÄØPM
42101-7245686-0
Mahnoor Arif6:29‚ÄØPM
4220178140796
Muhammad Haris Bin Khalid6:29‚ÄØPM
4210101244031
Ali Mehdi6:29‚ÄØPM
4220193871331
MAAZ AHMED6:30‚ÄØPM
4220181749601
Mohsin Kamal6:30‚ÄØPM
4230108855633
Suhail Arif6:30‚ÄØPM
Suhail Arif HUssain
Suhail Arif HUssain 4220176777201
Farah Asif6:31‚ÄØPM
37406-8087666-2
Engr Mahmood Ul Hassan6:31‚ÄØPM
4250185234859
Raheel Sadruddin6:31‚ÄØPM
4210129790553
Saad Shoaib6:31‚ÄØPM
4130414016931
Iqra Talha6:32‚ÄØPM
6110120315128
Arsalan Shaikh6:32‚ÄØPM
42201-6205339-3
Daniyal6:32‚ÄØPM
4250189782769
osama saleem6:34‚ÄØPM
4220182861439
ehzam ahmed6:34‚ÄØPM
4220176323111
Zubair ,6:37‚ÄØPM
3720117887067
usama hanif6:39‚ÄØPM
4210132209059
Usama Ahmed6:43‚ÄØPM
6110196883915
Farooq Ahmad6:43‚ÄØPM
3520294446451
Syed Muzammil Haider6:43‚ÄØPM
4210149039311
Ahmed Ali6:43‚ÄØPM
42101-0724035-9
Aijaz Ahmed6:43‚ÄØPM
4520691925699
ShahzadAzam Hashmi6:43‚ÄØPM
36302-4791284-7
Mahnoor Arif6:43‚ÄØPM
4220178140796
Suhail Arif6:43‚ÄØPM
Suhail ARfi Hussain 4220176777201
Abdulrafay Memon6:43‚ÄØPM
4520434839071
osama saleem6:43‚ÄØPM
4220182861439
Masood M. Khokhar6:44‚ÄØPM
4250148082389
Abdulrafay Memon6:44‚ÄØPM
4520434839071
Kamran Younus6:44‚ÄØPM
42301-2227082-1
salman soorani6:44‚ÄØPM
4210124505207
Abdul Mannan Khan6:45‚ÄØPM
4220143572841
Abdulrafay Memon6:47‚ÄØPM
4520434839071
Mohsin Kamal6:47‚ÄØPM
4230108855633
MARYAM RASHID6:47‚ÄØPM
4210198548420
Sheza Shams6:48‚ÄØPM
42201-0218814-0
Aijaz Ahmed6:48‚ÄØPM
45206919256999
4520691925699
sadia faiyaz6:49‚ÄØPM
4210157421004
upq-oxma-vmi
"""
df15= attendance(x)
print(len(df15))
df15['c15'] = 1
df15.head()

56

            CNIC  c15
0  4520282632947    1
1  4210107240359    1
2  3740680876662    1
3  4520434839071    1
4  4130414016931    1

In [18]:
x = """
Suhail Arif2:45‚ÄØPM
yes
Nasir Ali2:45‚ÄØPM
Yes.. voice aa rhi hai
Suhail Arif2:45‚ÄØPM
sir
Sadaf Tirmizi2:48‚ÄØPM
4210172467310
Masood M. Khokhar2:48‚ÄØPM
42501-4808238-9
Misbah Sabir2:49‚ÄØPM
no
Muneeb Bhania2:50‚ÄØPM
4210138182987
Abdul Haseeb Khan2:50‚ÄØPM
4220103084339
Ayaz Muhammad2:50‚ÄØPM
4520282632947
Areeba Ghazal2:50‚ÄØPM
4220108354184
M. A. Miher2:50‚ÄØPM
3720117887067
Areeba Ghazal2:50‚ÄØPM
areebaghazal
Muneeb Bhania2:51‚ÄØPM
4250177756968
Misbah Sabir2:51‚ÄØPM
yes sir
mere pas hogae
Suhail Arif2:51‚ÄØPM
yes
Raheel Sadruddin2:54‚ÄØPM
RECORDING HO RAHI HAI KE NAHI
Imran Karim2:54‚ÄØPM
4210103758455
Nasir Ali2:56‚ÄØPM
4330401845851
Abdul Mannan Khan2:59‚ÄØPM
4220143572841
Munir Mirza3:05‚ÄØPM
4210105756299
Suhail Arif3:05‚ÄØPM
Suhail Arif Hussain 4220176777201
Ali Affan Yaqoob3:05‚ÄØPM
42101-5031761-9
MAAZ AHMED3:06‚ÄØPM
attendance
4220181749601
Mahnoor Arif3:06‚ÄØPM
4220178140796
Munir Mirza3:07‚ÄØPM
4220102372205
Iqra Talha3:07‚ÄØPM
6110120315128
Wahid Khan3:07‚ÄØPM
4210116935049
Dr Nadeem Shah3:10‚ÄØPM
4130464926599
sadia faiyaz3:10‚ÄØPM
4210157421004
Owais Ahmed3:14‚ÄØPM
440103194893
Athar Khalid3:14‚ÄØPM
4210158892613
Owais Ahmed3:14‚ÄØPM
Crrection: 4220103194893
Muneeb Bhania3:18‚ÄØPM
4250177756968
4210138182987
Hassan Qamar3:18‚ÄØPM
4220110629561
Abdulrafay Memon3:19‚ÄØPM
45204-3483907-1
Farooq Ahmad3:19‚ÄØPM
3520294446451
MARYAM RASHID3:20‚ÄØPM
4210198548420
Hassan Saleem3:26‚ÄØPM
4210199525535
Fahad Aziz Khan3:31‚ÄØPM
4220195795065
Fahad Aziz Khan
Mohsin Kamal3:31‚ÄØPM
4230108855633
Areeba Ghazal3:37‚ÄØPM
4220408354184    areeba ghazal
Raja Waleed3:37‚ÄØPM
42201-8855051-5
Masood M. Khokhar3:37‚ÄØPM
4250148082389
Ahmed Ali3:39‚ÄØPM
42101-0724035-9
Engr Mahmood Ul Hassan3:39‚ÄØPM
4250185234859
Maria Noor Amjad3:41‚ÄØPM
6110119569820
salman soorani3:41‚ÄØPM
4210124505207
Sadiq Fazal3:42‚ÄØPM
42101-7245686-0
Misbah Sabir3:42‚ÄØPM
42101-5802137-4
Muneeb Bhania3:43‚ÄØPM
4250177756968
4210138182987
osama saleem3:46‚ÄØPM
4220182861439
osama saleem3:46‚ÄØPM
4220182861439
salman soorani3:51‚ÄØPM
4210124505207
Ahsan Fayyaz3:52‚ÄØPM
4220115069023
ShahzadAzam Hashmi3:55‚ÄØPM
3630247912847
Ali Mehdi3:57‚ÄØPM
4220193871331
Aijaz Ahmed4:00‚ÄØPM
4520691925699
Zubair ,4:00‚ÄØPM
1310104942039
Umer Fariq4:01‚ÄØPM
4220122685447
Arsalan Shaikh4:02‚ÄØPM
42201-6205339-3
Muhammad Uzair4:12‚ÄØPM
4210125481117
Raheel Sadruddin4:14‚ÄØPM
4210129790553
Usama Ahmed4:14‚ÄØPM
6110196883915
Mohsin Kamal4:14‚ÄØPM
4230108855633
Abdulrafay Memon4:14‚ÄØPM
4520434839071
Noor Saba4:14‚ÄØPM
4220187822116
MARYAM RASHID4:14‚ÄØPM
4210198548420
Mahnoor Arif4:14‚ÄØPM
4220178140796
Masood M. Khokhar4:14‚ÄØPM
42501-4808238-9
Ali Affan Yaqoob4:14‚ÄØPM
4210150317619
Ali Jilani4:14‚ÄØPM
4220114056719
usama hanif4:14‚ÄØPM
4210132209059
SHAHRUKH KHAN4:14‚ÄØPM
4210105390867
Kamran Younus4:14‚ÄØPM
42301-2227082-1
Syed Muzammil Haider4:14‚ÄØPM
4210149039311
sadia faiyaz4:15‚ÄØPM
4210157421004
Suhail Arif4:15‚ÄØPM
suhail arif 4220176777201
Sheza Shams4:15‚ÄØPM
42201-0218814-0
upq-oxma-vmi
4250189782769

"""

df16= attendance(x)
print(len(df16))
df16['c16'] = 1
df16.head()

57

            CNIC  c16
0  4220108354184    1
1  4210105390867    1
2  4220103084339    1
3  4520282632947    1
4  4520434839071    1

In [21]:
x = """
MAAZ AHMED5:14‚ÄØPM
no sound
salman soorani5:15‚ÄØPM
4210124505207
Munir Mirza5:16‚ÄØPM
4210105756299
Abdul Haseeb Khan5:18‚ÄØPM
4220103084339
Misbah Sabir5:18‚ÄØPM
42101-5802137-4
M. A. Miher5:19‚ÄØPM
3720117887067
Misbah Sabir5:19‚ÄØPM
yes
Munir Mirza5:19‚ÄØPM
4220102372205
Owais Ahmed5:23‚ÄØPM
4220103194893
Hassan Qamar5:23‚ÄØPM
4220110629561
MAAZ AHMED5:24‚ÄØPM
4220181749601
Ali Nawaz5:24‚ÄØPM
4220157226073
Engr Mahmood Ul Hassan5:26‚ÄØPM
4250185234859
Arsalan Shaikh5:26‚ÄØPM
4220162053393
ShahzadAzam Hashmi5:32‚ÄØPM
3630247912847
salman soorani5:32‚ÄØPM
4210124505207
Ali Jilani5:33‚ÄØPM
4220114056719
Muhammad Uzair5:34‚ÄØPM
42101-2548111-7
Ahmed Ali5:34‚ÄØPM
42101-0724035-9
Muneeb Bhania5:36‚ÄØPM
4250177756968
4210138182987
Iqra Talha5:41‚ÄØPM
6110120315128
Sadaf Tirmizi5:56‚ÄØPM
42101-7246731-0
42101-7245686-0
Maria Noor Amjad6:04‚ÄØPM
6110119569820
Ali Mehdi6:08‚ÄØPM
4220193871331
Dr Nadeem Shah6:09‚ÄØPM
4130464926599
Athar Khalid6:10‚ÄØPM
4210158892613
Zubair ,6:10‚ÄØPM
1310104942039
Noor Saba6:11‚ÄØPM
4220187822116
osama saleem6:18‚ÄØPM
4220182861439
Ahmed Ali6:18‚ÄØPM
42101-0724035-9
Noman Younus6:19‚ÄØPM
4220102372205
Aijaz Ahmed6:22‚ÄØPM
4520691925699
salman soorani6:23‚ÄØPM
4210124505207
wardah siddiqui6:23‚ÄØPM
4210166120772
MAAZ AHMED6:34‚ÄØPM
4220181749601
Fahad Aziz Khan6:34‚ÄØPM
4220195795065
Ahsan Fayyaz6:34‚ÄØPM
4220115069023
Usama Ahmed6:34‚ÄØPM
6110196883915
Sheza Shams6:35‚ÄØPM
42201-0218814-0
Mahnoor Arif6:35‚ÄØPM
4220178140796
Raheel Sadruddin6:35‚ÄØPM
4210129790553
salman soorani6:35‚ÄØPM
4210124505207
Syed Muzammil Haider6:35‚ÄØPM
4210149039311
Saad Shoaib6:35‚ÄØPM
41034-1401683-1
Ali Affan Yaqoob6:35‚ÄØPM
4210150317619
Mohsin Kamal6:35‚ÄØPM
4230108855633
SHAHRUKH KHAN6:35‚ÄØPM
4210105390867
Umer Fariq6:35‚ÄØPM
4220122685447
Raja Waleed6:35‚ÄØPM
4220188550515
Iqra Talha6:35‚ÄØPM
6110120315128
Athar Khalid6:35‚ÄØPM
4210132209059 usama
wardah siddiqui6:35‚ÄØPM
4210166120772
Hassan Qamar6:35‚ÄØPM
4220110629561
ShahzadAzam Hashmi6:35‚ÄØPM
36302-4791284-7
Raheel Sadruddin6:35‚ÄØPM
42301-2227082-1
MARYAM RASHID6:35‚ÄØPM
4210198548420
Suhail Arif6:36‚ÄØPM
Suhail Arif Hussain 4220176777201
sadia faiyaz6:36‚ÄØPM
4210157421004
Ali Affan Yaqoob6:36‚ÄØPM
42101-5031761-9
Ali Jilani6:36‚ÄØPM
4220114056719
Masood M. Khokhar6:36‚ÄØPM
42501-4808238-9
Suhail Arif6:36‚ÄØPM
hAFIZ aBDUL wAHID 4210116935049
Farooq Ahmad6:37‚ÄØPM
3520294446451
Daniyal6:37‚ÄØPM
4250189782769
Muhammad Haris Bin Khalid6:39‚ÄØPM
4210101244031
Abdulrafay Memon6:41‚ÄØPM
4520434839071
Masood M. Khokhar6:45‚ÄØPM
4250148082389
Mohsin Kamal6:47‚ÄØPM
4230108855633
salman soorani6:47‚ÄØPM
4210124505207
Ahmed Ali6:47‚ÄØPM
42101-0724035-9
MAAZ AHMED6:48‚ÄØPM
4220181749601
Farooq Ahmad6:48‚ÄØPM
3520294446451
Misbah Sabir6:48‚ÄØPM
4210158021374
Syed Muzammil Haider6:48‚ÄØPM
4210149039311
ShahzadAzam Hashmi6:48‚ÄØPM
3630247912847
Ahsan Fayyaz6:48‚ÄØPM
4220115069023
Ali Jilani6:48‚ÄØPM
4220114056719
Ali Nawaz6:48‚ÄØPM
4220157226073
Raja Waleed6:48‚ÄØPM
4220188550515
Zubair ,6:48‚ÄØPM
1310104942039
Engr Mahmood Ul Hassan6:48‚ÄØPM
4250185234859
Dr Nadeem Shah6:48‚ÄØPM
4130464926599
Owais Ahmed6:48‚ÄØPM
4220103194893
Ali Mehdi6:48‚ÄØPM
4220193871331
Suhail Arif6:48‚ÄØPM
4220176777201
Ali Affan Yaqoob6:48‚ÄØPM
4210157421004
osama saleem6:48‚ÄØPM
4220182861439
Sadaf Tirmizi6:48‚ÄØPM
42101-7246731-0
Ali Affan Yaqoob6:48‚ÄØPM
4210150317619
Sadaf Tirmizi6:48‚ÄØPM
42101-7245686-0
Arsalan Shaikh6:49‚ÄØPM
42201-6205339-3
Saad Shoaib6:49‚ÄØPM
41304-1401693-1
upq-oxma-vmi
"""

df17= attendance(x)
print(len(df17))
df17['c17'] = 1
df17.head()

55

            CNIC  c17
0  4210105390867    1
1  4220103084339    1
2  4520434839071    1
3  4220102188140    1
4  4220122685447    1

# Final

In [22]:
df = df1.merge(df2,on='CNIC', how='outer').fillna(0).merge(
    df3, on="CNIC",how="outer"
).fillna(0).merge(
df4, on="CNIC", how='outer'
).fillna(0).merge(
df5, on="CNIC", how='outer'
).fillna(0).merge(
df6, on="CNIC", how='outer'
).fillna(0).merge(
df7, on="CNIC", how='outer'
).fillna(0).merge(
df8, on="CNIC", how='outer'
).fillna(0).merge(
df9, on="CNIC", how='outer'
).fillna(0).merge(
df10, on="CNIC", how='outer'
).fillna(0).merge(
df11, on="CNIC", how='outer'
).fillna(0).merge(
df12, on="CNIC", how='outer'
).fillna(0).merge(
df13, on="CNIC", how='outer'
).fillna(0).merge(
df14, on="CNIC", how='outer'
).fillna(0).merge(
df15, on="CNIC", how='outer'
).fillna(0).merge(
df16, on="CNIC", how='outer'
).fillna(0).merge(
df17, on="CNIC", how='outer'
).fillna(0)



df['total'] = df.iloc[:,1:].astype(int).sum(axis=1)
df.sort_values(by="total", inplace=True, ascending=False)
df.reset_index(drop=True,inplace=True)
print(len(df))
display(df.iloc[:,1:-1].sum(axis=0))
display(df.head(60))
display(df.iloc[60:,:])

100

c1     58.0
c2     67.0
c3     66.0
c4     65.0
c5     70.0
c6     71.0
c7     68.0
c8     68.0
c9     63.0
c10    67.0
c11    67.0
c12    49.0
c13    51.0
c14    54.0
c15    56.0
c16    57.0
c17    55.0
dtype: float64

,CNIC,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14,c15,c16,c17,total
0,4250185234859,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,17
1,4210129790553,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,17
2,4210124505207,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,17
3,4220114056719,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,17
4,4210105390867,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,17
5,3630247912847,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,17
6,1310104942039,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,17
7,4220176777201,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,17
8,4220182861439,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,17
9,4210132209059,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,17
10,4210150317619,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,17
11,4230108855633,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,17
12,4250189782769,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16
13,4210105756299,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,16
14,4210116935049,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,16
15,4220187822116,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,16
16,4220102188140,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16
17,4210107240359,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16
18,4220110629561,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16
19,4210158021374,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,16
20,4210157421004,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16
21,4130464926599,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16
22,4220102372205,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,15
23,4520691925699,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,15
24,4220122685447,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,15
25,4210125481117,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,15
26,4220103194893,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,15
27,4230122270821,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,15
28,4220178140796,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,15
29,4220193871331,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,15
30,3720117887067,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,14
31,4520434839071,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,14
32,6110120315128,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,14
33,4210149039311,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,14
34,4210172456860,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,14
35,4220103084339,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,14
36,4210172467310,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,14
37,4210166120772,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,14
38,6110119569820,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,14
39,4220176323111,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,14
40,4210113165975,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,13
41,3740680876662,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,13
42,4210158892613,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,13
43,6110196883915,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,13
44,4220162053393,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,13
45,4220143572841,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,13
46,4220195795065,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,13
47,4210199525535,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,13
48,4200044884823,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,13
49,4220188550515,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,13
50,4210138182987,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,12
51,4130414016931,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,12
52,4330401845851,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,12
53,4220115069023,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,12
54,4220181749601,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,12
55,4250177756968,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,12
56,4130356133125,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,11
57,3520294446451,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,11
58,4220141892019,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,11
59,4220157226073,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,11

,CNIC,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14,c15,c16,c17,total
60,4250148082389,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,11
61,4520282632947,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,11
62,5540124860782,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,10
63,4210101244031,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,10
64,4220134664875,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,9
65,4210172457810,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9
66,4250181112217,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,9
67,3830155517583,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,9
68,4210131827012,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,9
69,4210198548420,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,9
70,4210192333399,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,9
71,4140703835369,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,8
72,4220108354184,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,7
73,4240134843465,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7
74,4240113406009,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7
75,4220115395943,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7
76,4320307738760,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6
77,3630230577559,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5
78,4220177849728,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4
79,4210195297779,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
80,4230135829705,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
81,4220195795061,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
82,4210103758455,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,2
83,5540134860782,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1
84,4220408354184,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1
85,4220178140496,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1
86,4220165053393,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1
87,4330301845851,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1
88,4220103372205,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1
89,4210149117409,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1
90,4420178140796,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
91,3831055517583,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
92,3740523718449,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
93,4120108835732,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
94,4220130549643,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
95,4210102810113,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
96,4250177756958,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
97,4220147830681,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
98,4120108836732,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
99,4103414016831,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1

In [20]:
17/71

0.23943661971830985